using JetBrains.Annotations;
using System.Reflection.PortableExecutable;
using Turbo.WIN63202407091256704579380.Parsers.Catalog;

namespace Turbo.WIN63202407091256704579380;

public static class MessageComposer
{
    public const int CantConnectMessageComposer = 858;
    public const int CloseConnectionMessageComposer = 2893;
    public const int FlatAccessibleMessageComposer = 431;
    public const int GamePlayerValueMessageComposer = 2376;
    public const int HanditemConfigurationMessageComposer = 1009;
    public const int OpenConnectionMessageComposer = 327;
    public const int RoomForwardMessageComposer = 2190;
    public const int RoomQueueStatusMessageComposer = 3088;
    public const int RoomReadyMessageComposer = 3024;
    public const int YouAreNotSpectatorMessageComposer = 2111;
    public const int YouArePlayingGameMessageComposer = 2495;
    public const int YouAreSpectatorMessageComposer = 2799;
    public const int BotCommandConfigurationComposer = 2621;
    public const int BotErrorComposer = 1527;
    public const int BotForceOpenContextMenuComposer = 3012;
    public const int BotSkillListUpdateComposer = 3748;
    public const int AvailabilityStatusMessageComposer = 3449;
    public const int InfoHotelClosedMessageComposer = 3892;
    public const int InfoHotelClosingMessageComposer = 2210;
    public const int LoginFailedHotelClosedMessageComposer = 3504;
    public const int MaintenanceStatusMessageComposer = 3126;
    public const int NewUserExperienceGiftOfferComposer = 3583;
    public const int NewUserExperienceNotCompleteComposer = 200;
    public const int SelectInitialRoomComposer = 3693;
    public const int JukeboxPlayListFullMessageComposer = 1683;
    public const int JukeboxSongDisksMessageComposer = 847;
    public const int NowPlayingMessageComposer = 3859;
    public const int OfficialSongIdMessageComposer = 2439;
    public const int PlayListMessageComposer = 3408;
    public const int PlayListSongAddedMessageComposer = 2805;
    public const int TraxSongInfoMessageComposer = 1271;
    public const int UserSongDisksInventoryMessageComposer = 517;
    public const int AchievementComposer = 1519;
    public const int AchievementsComposer = 404;
    public const int AchievementsScoreComposer = 1196;
    public const int CampaignCalendarDataMessageComposer = 3108;
    public const int CampaignCalendarDoorOpenedMessageComposer = 502;
    public const int BonusRareInfoMessageComposer = 2518;
    public const int BuildersClubFurniCountMessageComposer = 2449;
    public const int BuildersClubSubscriptionStatusMessageComposer = 3907;
    public const int BundleDiscountRulesetMessageComposer = 1018;
    public const int CatalogIndexMessageComposer = 3262;
    public const int CatalogPageMessageComposer = 2308;
    public const int CatalogPageWithEarliestExpiryMessageComposer = 1297;
    public const int CatalogPublishedMessageComposer = 1411;
    public const int ClubGiftInfoComposer = 1419;
    public const int ClubGiftSelectedComposer = 679;
    public const int GiftReceiverNotFoundComposer = 2923;
    public const int GiftWrappingConfigurationComposer = 3060;
    public const int HabboClubExtendOfferMessageComposer = 1444;
    public const int HabboClubOffersMessageComposer = 1227;
    public const int LimitedEditionSoldOutComposer = 3675;
    public const int LimitedOfferAppearingNextMessageComposer = 1397;
    public const int NotEnoughBalanceMessageComposer = 2200;
    public const int ProductOfferComposer = 1412;
    public const int PurchaseErrorMessageComposer = 481;
    public const int PurchaseNotAllowedMessageComposer = 1154;
    public const int PurchaseOKMessageComposer = 2662;
    public const int RoomAdPurchaseInfoComposer = 1008;
    public const int SeasonalCalendarDailyOfferMessageComposer = 472;
    public const int SellablePetPalettesMessageComposer = 3988;
    public const int SnowWarGameTokensMessageComposer = 3720;
    public const int TargetedOfferComposer = 1005;
    public const int TargetedOfferNotFoundComposer = 2976;
    public const int VoucherRedeemErrorMessageComposer = 3059;
    public const int VoucherRedeemOkMessageComposer = 1764;
    public const int CallForHelpDisabledNotifyMessageComposer = 1076;
    public const int CallForHelpPendingCallsDeletedMessageComposer = 1879;
    public const int CallForHelpPendingCallsMessageComposer = 878;
    public const int CallForHelpReplyMessageComposer = 2141;
    public const int CallForHelpResultMessageComposer = 3536;
    public const int ChatReviewSessionDetachedMessageComposer = 2691;
    public const int ChatReviewSessionOfferedToGuideMessageComposer = 2422;
    public const int ChatReviewSessionResultsMessageComposer = 1438;
    public const int ChatReviewSessionStartedMessageComposer = 1145;
    public const int ChatReviewSessionVotingStatusMessageComposer = 1646;
    public const int GuideOnDutyStatusMessageComposer = 1349;
    public const int GuideReportingStatusMessageComposer = 320;
    public const int GuideSessionAttachedMessageComposer = 2044;
    public const int GuideSessionDetachedMessageComposer = 1797;
    public const int GuideSessionEndedMessageComposer = 2814;
    public const int GuideSessionErrorMessageComposer = 713;
    public const int GuideSessionInvitedToGuideRoomMessageComposer = 2130;
    public const int GuideSessionMessageMessageComposer = 2154;
    public const int GuideSessionPartnerIsTypingMessageComposer = 529;
    public const int GuideSessionRequesterRoomMessageComposer = 1699;
    public const int GuideSessionStartedMessageComposer = 1485;
    public const int GuideTicketCreationResultMessageComposer = 1772;
    public const int GuideTicketResolutionMessageComposer = 1961;
    public const int IssueCloseNotificationMessageComposer = 3603;
    public const int QuizDataMessageComposer = 3628;
    public const int QuizResultsMessageComposer = 3581;
    public const int Game2ArenaEnteredMessageComposer = 2559;
    public const int Game2EnterArenaFailedMessageComposer = 3453;
    public const int Game2EnterArenaMessageComposer = 3481;
    public const int Game2GameChatFromPlayerMessageComposer = 2661;
    public const int Game2GameEndingMessageComposer = 2677;
    public const int Game2GameRejoinMessageComposer = 1795;
    public const int Game2PlayerExitedGameArenaMessageComposer = 3113;
    public const int Game2PlayerRematchesMessageComposer = 3774;
    public const int Game2StageEndingMessageComposer = 2962;
    public const int Game2StageLoadMessageComposer = 1278;
    public const int Game2StageRunningMessageComposer = 2854;
    public const int Game2StageStartingMessageComposer = 1256;
    public const int Game2StageStillLoadingMessageComposer = 791;
    public const int AreaHideMessageComposer = 137;
    public const int CustomStackingHeightUpdateMessageComposer = 3063;
    public const int CustomUserNotificationMessageComposer = 2342;
    public const int DiceValueMessageComposer = 2689;
    public const int FurniRentOrBuyoutOfferMessageComposer = 3208;
    public const int GuildFurniContextMenuInfoMessageComposer = 631;
    public const int OneWayDoorStatusMessageComposer = 131;
    public const int OpenPetPackageRequestedMessageComposer = 3844;
    public const int OpenPetPackageResultMessageComposer = 3505;
    public const int PresentOpenedMessageComposer = 3920;
    public const int RentableSpaceRentFailedMessageComposer = 3517;
    public const int RentableSpaceRentOkMessageComposer = 2240;
    public const int RentableSpaceStatusMessageComposer = 2464;
    public const int RequestSpamWallPostItMessageComposer = 975;
    public const int RoomDimmerPresetsMessageComposer = 3598;
    public const int RoomMessageNotificationMessageComposer = 731;
    public const int YoutubeControlVideoMessageComposer = 106;
    public const int YoutubeDisplayPlaylistsMessageComposer = 1164;
    public const int YoutubeDisplayVideoMessageComposer = 3169;
    public const int ErrorReportComposer = 657;
    public const int TradeOpenFailedComposer = 2049;
    public const int TradeSilverFeeMessageComposer = 1395;
    public const int TradeSilverSetMessageComposer = 939;
    public const int TradingAcceptComposer = 1011;
    public const int TradingCloseComposer = 308;
    public const int TradingCompletedComposer = 1376;
    public const int TradingConfirmationComposer = 1564;
    public const int TradingItemListComposer = 2807;
    public const int TradingNotOpenComposer = 2498;
    public const int TradingOpenComposer = 1;
    public const int TradingOtherNotAllowedComposer = 403;
    public const int TradingYouAreNotAllowedComposer = 3960;
    public const int MarketplaceBuyOfferResultComposer = 2674;
    public const int MarketplaceCancelOfferResultComposer = 2417;
    public const int MarketplaceCanMakeOfferResult = 695;
    public const int MarketplaceConfigurationComposer = 381;
    public const int MarketplaceItemStatsComposer = 261;
    public const int MarketplaceMakeOfferResult = 2627;
    public const int MarketPlaceOffersComposer = 1578;
    public const int MarketPlaceOwnOffersComposer = 2425;
    public const int CitizenshipVipOfferPromoEnabledComposer = 2670;
    public const int PerkAllowancesMessageComposer = 1330;
    public const int RoomEntryTileMessageComposer = 1580;
    public const int RoomOccupiedTilesMessageComposer = 2802;
    public const int HotLooksMessageComposer = 3229;
    public const int FriendFurniCancelLockMessageComposer = 45;
    public const int FriendFurniOtherLockConfirmedMessageComposer = 3348;
    public const int FriendFurniStartConfirmationMessageComposer = 585;
    public const int CreditBalanceComposer = 1604;
    public const int AvatarEffectMessageComposer = 1767;
    public const int CarryObjectMessageComposer = 1299;
    public const int DanceMessageComposer = 558;
    public const int ExpressionMessageComposer = 3855;
    public const int SleepMessageComposer = 807;
    public const int UseObjectMessageComposer = 2675;
    public const int Game2AccountGameStatusMessageComposer = 3661;
    public const int Game2GameCancelledMessageComposer = 3260;
    public const int Game2GameCreatedMessageComposer = 674;
    public const int Game2GameDirectoryStatusMessageComposer = 2835;
    public const int Game2GameLongDataMessageComposer = 1753;
    public const int Game2GameStartedMessageComposer = 2590;
    public const int Game2InArenaQueueMessageComposer = 2813;
    public const int Game2JoiningGameFailedMessageComposer = 668;
    public const int Game2StartCounterMessageComposer = 873;
    public const int Game2StartingGameFailedMessageComposer = 865;
    public const int Game2StopCounterMessageComposer = 1714;
    public const int Game2UserBlockedMessageComposer = 2067;
    public const int Game2UserJoinedGameMessageComposer = 2389;
    public const int Game2UserLeftGameMessageComposer = 795;
    public const int ChangeUserNameResultMessageComposer = 3732;
    public const int CheckUserNameResultMessageComposer = 3053;
    public const int FigureUpdateComposer = 836;
    public const int WardrobeMessageComposer = 3610;
    public const int CollectableMintableItemTypesMessageComposer = 3343;
    public const int CollectibleMintableItemResultMessageComposer = 2146;
    public const int CollectibleMintingEnabledMessageComposer = 573;
    public const int CollectibleMintTokenCountMessageComposer = 3414;
    public const int CollectibleMintTokenOffersMessageComposer = 3079;
    public const int CollectibleWalletAddressesMessageComposer = 1209;
    public const int EmeraldBalanceMessageComposer = 180;
    public const int NftBonusItemClaimResultMessageComposer = 2920;
    public const int NftCollectionsMessageComposer = 3551;
    public const int NftCollectionsScoreMessageComposer = 2016;
    public const int NftRewardItemClaimResultMessageComposer = 3117;
    public const int NftTransferAssetsResultMessageComposer = 3555;
    public const int NftTransferFeeMessageComposer = 3299;
    public const int SilverBalanceMessageComposer = 3226;
    public const int AcceptFriendResultComposer = 3125;
    public const int ConsoleMessageHistoryComposer = 1819;
    public const int FindFriendsProcessResultComposer = 1122;
    public const int FollowFriendFailedComposer = 2508;
    public const int FriendListFragmentMessageComposer = 1142;
    public const int FriendListUpdateComposer = 3966;
    public const int FriendNotificationComposer = 1928;
    public const int FriendRequestsComposer = 3313;
    public const int HabboSearchResultComposer = 3471;
    public const int InstantMessageErrorComposer = 3498;
    public const int MessengerErrorComposer = 687;
    public const int MessengerInitComposer = 1623;
    public const int MiniMailNewMessageComposer = 279;
    public const int MiniMailUnreadCountComposer = 3856;
    public const int NewConsoleMessageComposer = 2935;
    public const int NewFriendRequestComposer = 1207;
    public const int RoomInviteErrorComposer = 3994;
    public const int RoomInviteComposer = 2514;
    public const int InterstitialMessageComposer = 3430;
    public const int RoomAdErrorComposer = 2850;
    public const int ForumDataMessageComposer = 619;
    public const int ForumsListMessageComposer = 816;
    public const int ForumThreadsMessageComposer = 3199;
    public const int PostMessageMessageComposer = 3669;
    public const int PostThreadMessageComposer = 3518;
    public const int ThreadMessagesMessageComposer = 647;
    public const int UnreadForumsCountMessageComposer = 3270;
    public const int UpdateMessageMessageComposer = 2551;
    public const int UpdateThreadMessageComposer = 3579;
    public const int CreditVaultStatusMessageComposer = 2861;
    public const int IncomeRewardClaimResponseMessageComposer = 1013;
    public const int IncomeRewardStatusMessageComposer = 33;
    public const int BotAddedToInventoryComposer = 2843;
    public const int BotInventoryComposer = 2161;
    public const int BotRemovedFromInventoryComposer = 1266;
    public const int BadgePointLimitsComposer = 1730;
    public const int BadgeReceivedComposer = 442;
    public const int BadgesComposer = 1993;
    public const int IsBadgeRequestFulfilledComposer = 2039;
    public const int NavigatorCollapsedCategoriesMessageComposer = 1396;
    public const int NavigatorLiftedRoomsComposer = 1310;
    public const int NavigatorMetaDataComposer = 3718;
    public const int NavigatorSavedSearchesComposer = 1134;
    public const int NavigatorSearchResultBlocksComposer = 1245;
    public const int NewNavigatorPreferencesComposer = 3658;
    public const int BannedUsersFromRoomComposer = 2457;
    public const int FlatControllerAddedComposer = 3437;
    public const int FlatControllerRemovedComposer = 3259;
    public const int FlatControllersComposer = 3031;
    public const int MuteAllInRoomComposer = 63;
    public const int NoSuchFlatComposer = 1423;
    public const int RoomSettingsDataComposer = 1296;
    public const int RoomSettingsErrorComposer = 3613;
    public const int RoomSettingsSavedComposer = 3447;
    public const int RoomSettingsSaveErrorComposer = 3230;
    public const int ShowEnforceRoomCategoryDialogComposer = 1069;
    public const int UserUnbannedFromRoomComposer = 2869;
    public const int PollContentsComposer = 2117;
    public const int PollErrorComposer = 1487;
    public const int PollOfferComposer = 3961;
    public const int QuestionAnsweredComposer = 3825;
    public const int QuestionComposer = 497;
    public const int QuestionFinishedComposer = 1774;
    public const int Game2FullGameStatusMessageComposer = 3054;
    public const int Game2GameStatusMessageComposer = 25;
    public const int CompetitionEntrySubmitResultMessageComposer = 3040;
    public const int CompetitionVotingInfoMessageComposer = 1118;
    public const int CurrentTimingCodeMessageComposer = 3382;
    public const int IsUserPartOfCompetitionMessageComposer = 1002;
    public const int NoOwnedRoomsAlertMessageComposer = 770;
    public const int SecondsUntilMessageComposer = 145;
    public const int CfhChatlogComposer = 2319;
    public const int IssueDeletedMessageComposer = 1552;
    public const int IssueInfoMessageComposer = 3077;
    public const int IssuePickFailedMessageComposer = 1454;
    public const int ModeratorActionResultMessageComposer = 2741;
    public const int ModeratorCautionComposer = 3983;
    public const int ModeratorInitMessageComposer = 30;
    public const int ModeratorMessageComposer = 2709;
    public const int ModeratorRoomInfoComposer = 2318;
    public const int ModeratorToolPreferencesComposer = 334;
    public const int ModeratorUserInfoComposer = 226;
    public const int RoomChatlogComposer = 3160;
    public const int RoomVisitsComposer = 3619;
    public const int UserBannedMessageComposer = 298;
    public const int UserChatlogComposer = 104;
    public const int CraftableProductsMessageComposer = 2557;
    public const int CraftingRecipeMessageComposer = 2288;
    public const int CraftingRecipesAvailableMessageComposer = 2429;
    public const int CraftingResultMessageComposer = 1343;
    public const int ChatMessageComposer = 1632;
    public const int FloodControlMessageComposer = 3585;
    public const int RemainingMutePeriodComposer = 3405;
    public const int RoomChatSettingsMessageComposer = 1156;
    public const int RoomFilterSettingsMessageComposer = 183;
    public const int ShoutMessageComposer = 3554;
    public const int UserTypingMessageComposer = 1780;
    public const int WhisperMessageComposer = 2834;
    public const int ConfirmBreedingRequestComposer = 2346;
    public const int ConfirmBreedingResultComposer = 929;
    public const int GoToBreedingNestFailureComposer = 1110;
    public const int NestBreedingSuccessComposer = 3758;
    public const int PetAddedToInventoryComposer = 1346;
    public const int PetBreedingComposer = 3006;
    public const int PetInventoryComposer = 2327;
    public const int PetReceivedMessageComposer = 2771;
    public const int PetRemovedFromInventoryComposer = 3506;
    public const int CameraPublishStatusMessageComposer = 1061;
    public const int CameraPurchaseOKMessageComposer = 1267;
    public const int CameraStorageUrlMessageComposer = 3134;
    public const int CompetitionStatusMessageComposer = 365;
    public const int InitCameraMessageComposer = 263;
    public const int ThumbnailStatusMessageComposer = 3679;
    public const int CancelMysteryBoxWaitMessageComposer = 3819;
    public const int GotMysteryBoxPrizeMessageComposer = 1135;
    public const int MysteryBoxKeysMessageComposer = 351;
    public const int ShowMysteryBoxWaitMessageComposer = 692;
    public const int WiredAllVariableHoldersComposer = 1923;
    public const int WiredAllVariablesDiffsComposer = 3635;
    public const int WiredAllVariablesHashComposer = 369;
    public const int WiredErrorLogsComposer = 652;
    public const int WiredMenuErrorComposer = 1796;
    public const int WiredPermissionsComposer = 3444;
    public const int WiredRoomSettingsComposer = 2014;
    public const int WiredRoomStatsComposer = 3043;
    public const int WiredVariablesForObjectComposer = 1084;
    public const int AuthenticationOKMessageComposer = 2323;
    public const int CompleteDiffieHandshakeComposer = 3777;
    public const int DisconnectReasonComposer = 4000;
    public const int GenericErrorComposer = 598;
    public const int IdentityAccountsComposer = 1417;
    public const int InitDiffieHandshakeComposer = 771;
    public const int IsFirstLoginOfDayComposer = 3129;
    public const int NoobnessLevelMessageComposer = 1916;
    public const int PingMessageComposer = 658;
    public const int UniqueMachineIDComposer = 3974;
    public const int UserObjectComposer = 3048;
    public const int UserRightsMessageComposer = 1416;
    public const int CommunityVoteReceivedComposer = 867;
    public const int UserNftChatStylesMessageComposer = 1205;
    public const int UserNftWardrobeMessageComposer = 3442;
    public const int UserNftWardrobeSelectionMessageComposer = 2055;
    public const int LatencyPingResponseMessageComposer = 931;
    public const int CommunityGoalHallOfFameMessageComposer = 358;
    public const int CommunityGoalProgressMessageComposer = 352;
    public const int ConcurrentUsersGoalProgressMessageComposer = 2239;
    public const int EpicPopupMessageComposer = 3959;
    public const int QuestCancelledMessageComposer = 1673;
    public const int QuestCompletedMessageComposer = 677;
    public const int QuestDailyMessageComposer = 3775;
    public const int QuestMessageComposer = 3968;
    public const int QuestsMessageComposer = 3478;
    public const int SeasonalQuestsMessageComposer = 3187;
    public const int ActivityPointsMessageComposer = 2875;
    public const int ClubGiftNotificationComposer = 3139;
    public const int ElementPointerMessageComposer = 207;
    public const int HabboAchievementNotificationMessageComposer = 1287;
    public const int HabboActivityPointNotificationMessageComposer = 173;
    public const int HabboBroadcastMessageComposer = 3874;
    public const int InfoFeedEnableMessageComposer = 114;
    public const int MOTDNotificationComposer = 1823;
    public const int NotificationDialogMessageComposer = 440;
    public const int OfferRewardDeliveredMessageComposer = 840;
    public const int PetLevelNotificationComposer = 675;
    public const int RestoreClientMessageComposer = 3525;
    public const int UnseenItemsComposer = 1654;
    public const int PetBreedingResultComposer = 1128;
    public const int PetCommandsMessageComposer = 1318;
    public const int PetExperienceComposer = 2472;
    public const int PetFigureUpdateComposer = 2957;
    public const int PetInfoMessageComposer = 2619;
    public const int PetLevelUpdateComposer = 633;
    public const int PetPlacingErrorComposer = 2657;
    public const int PetRespectFailedComposer = 3002;
    public const int PetStatusUpdateComposer = 541;
    public const int AchievementResolutionCompletedMessageComposer = 134;
    public const int AchievementResolutionProgressMessageComposer = 1254;
    public const int AchievementResolutionsMessageComposer = 237;
    public const int PhoneCollectionStateMessageComposer = 3806;
    public const int TryPhoneNumberResultMessageComposer = 845;
    public const int TryVerificationCodeResultMessageComposer = 3929;
    public const int FigureSetIdsComposer = 464;
    public const int AccountPreferencesComposer = 2641;
    public const int Game2FriendsLeaderboardComposer = 3573;
    public const int Game2TotalGroupLeaderboardComposer = 2474;
    public const int Game2TotalLeaderboardComposer = 3769;
    public const int Game2WeeklyFriendsLeaderboardComposer = 3214;
    public const int Game2WeeklyGroupLeaderboardComposer = 3464;
    public const int Game2WeeklyLeaderboardComposer = 3392;
    public const int CfhSanctionMessageComposer = 2930;
    public const int CfhTopicsInitMessageComposer = 3778;
    public const int SanctionStatusComposer = 3696;
    public const int YouAreControllerMessageComposer = 3116;
    public const int YouAreNotControllerMessageComposer = 817;
    public const int YouAreOwnerMessageComposer = 3915;
    public const int AvatarEffectActivatedMessageComposer = 3383;
    public const int AvatarEffectAddedMessageComposer = 2194;
    public const int AvatarEffectExpiredMessageComposer = 1751;
    public const int AvatarEffectSelectedMessageComposer = 3158;
    public const int AvatarEffectsMessageComposer = 1119;
    public const int TalentLevelUpMessageComposer = 3764;
    public const int TalentTrackLevelMessageComposer = 2095;
    public const int TalentTrackMessageComposer = 1432;
    public const int UserClassificationMessageComposer = 3812;
    public const int AccountSafetyLockStatusChangeMessageComposer = 654;
    public const int ApproveNameMessageComposer = 1682;
    public const int ChangeEmailResultComposer = 586;
    public const int EmailStatusResultComposer = 712;
    public const int ExtendedProfileChangedMessageComposer = 3410;
    public const int ExtendedProfileMessageComposer = 919;
    public const int GroupDetailsChangedMessageComposer = 341;
    public const int GroupMembershipRequestedMessageComposer = 2258;
    public const int GuildCreatedMessageComposer = 2021;
    public const int GuildCreationInfoMessageComposer = 3731;
    public const int GuildEditFailedMessageComposer = 1820;
    public const int GuildEditInfoMessageComposer = 968;
    public const int GuildEditorDataMessageComposer = 1575;
    public const int GuildMemberFurniCountInHQMessageComposer = 1940;
    public const int GuildMemberMgmtFailedMessageComposer = 853;
    public const int GuildMembershipRejectedMessageComposer = 2217;
    public const int GuildMembershipsMessageComposer = 2196;
    public const int GuildMembershipUpdatedMessageComposer = 1593;
    public const int GuildMembersMessageComposer = 2029;
    public const int HabboGroupBadgesMessageComposer = 2798;
    public const int HabboGroupDeactivatedMessageComposer = 2260;
    public const int HabboGroupDetailsMessageComposer = 1569;
    public const int HabboGroupJoinFailedMessageComposer = 1124;
    public const int HabboUserBadgesMessageComposer = 3975;
    public const int HandItemReceivedMessageComposer = 889;
    public const int IgnoredUsersMessageComposer = 3326;
    public const int IgnoreResultMessageComposer = 2936;
    public const int InClientLinkMessageComposer = 2437;
    public const int PetRespectNotificationComposer = 2034;
    public const int PetSupplementedNotificationComposer = 2455;
    public const int RelationshipStatusInfoComposer = 3538;
    public const int RespectNotificationMessageComposer = 1429;
    public const int ScrSendKickbackInfoMessageComposer = 2969;
    public const int ScrSendUserInfoComposer = 937;
    public const int UserNameChangedMessageComposer = 2879;
    public const int PromoArticlesMessageComposer = 1875;
    public const int BuildersClubPlacementWarningMessageComposer = 3140;
    public const int FavoriteMembershipUpdateMessageComposer = 234;
    public const int FloorHeightMapMessageComposer = 1270;
    public const int FurnitureAliasesMessageComposer = 382;
    public const int HeightMapMessageComposer = 3492;
    public const int HeightMapUpdateMessageComposer = 2948;
    public const int ItemAddMessageComposer = 684;
    public const int ItemDataUpdateMessageComposer = 3011;
    public const int ItemRemoveMessageComposer = 1093;
    public const int ItemsMessageComposer = 3514;
    public const int ItemsStateUpdateMessageComposer = 316;
    public const int ItemStateUpdateMessageComposer = 3415;
    public const int ItemUpdateMessageComposer = 2101;
    public const int ObjectAddMessageComposer = 3122;
    public const int ObjectDataUpdateMessageComposer = 3007;
    public const int ObjectRemoveConfirmMessageComposer = 3314;
    public const int ObjectRemoveMessageComposer = 3233;
    public const int ObjectRemoveMultipleMessageComposer = 32;
    public const int ObjectsDataUpdateMessageComposer = 473;
    public const int ObjectsMessageComposer = 1572;
    public const int ObjectUpdateMessageComposer = 3075;
    public const int RoomEntryInfoMessageComposer = 2791;
    public const int RoomPropertyMessageComposer = 3633;
    public const int RoomVisualizationSettingsComposer = 3407;
    public const int SlideObjectBundleMessageComposer = 1661;
    public const int SpecialRoomEffectMessageComposer = 1440;
    public const int UserChangeMessageComposer = 2680;
    public const int UserRemoveMessageComposer = 2193;
    public const int UsersMessageComposer = 2846;
    public const int UserUpdateMessageComposer = 3911;
    public const int WiredMovementsMessageComposer = 3000;
    public const int CanCreateRoomComposer = 3627;
    public const int CanCreateRoomComposerEvent = 1722;
    public const int CategoriesWithVisitorCountComposer = 965;
    public const int CompetitionRoomsDataMessageComposer = 739;
    public const int ConvertedRoomIdComposer = 574;
    public const int DoorbellMessageComposer = 1546;
    public const int FavouriteChangedComposer = 3523;
    public const int FavouritesComposer = 2676;
    public const int FlatAccessDeniedMessageComposer = 1906;
    public const int FlatCreatedComposer = 1489;
    public const int GetGuestRoomResultComposer = 2048;
    public const int GuestRoomSearchResultComposer = 34;
    public const int NavigatorSettingsComposer = 895;
    public const int OfficialRoomsComposer = 215;
    public const int PopularRoomTagsResultComposer = 3210;
    public const int RoomComposerCancelEvent = 805;
    public const int RoomComposerEvent = 3037;
    public const int RoomInfoUpdatedComposer = 1773;
    public const int RoomRatingComposer = 1183;
    public const int UserComposerCatsEvent = 804;
    public const int UserFlatCatsComposer = 523;
    public const int FurniListAddOrUpdateComposer = 3595;
    public const int FurniListComposer = 3550;
    public const int FurniListInvalidateComposer = 2386;
    public const int FurniListRemoveComposer = 3691;
    public const int PostItPlacedComposer = 2405;
    public const int OpenComposer = 1674;
    public const int WiredFurniActionComposer = 996;
    public const int WiredFurniAddonComposer = 367;
    public const int WiredFurniConditionComposer = 3104;
    public const int WiredFurniSelectorComposer = 588;
    public const int WiredFurniTriggerComposer = 893;
    public const int WiredFurniVariableComposer = 146;
    public const int WiredRewardResultMessageComposer = 1758;
    public const int WiredSaveSuccessComposer = 1373;
    public const int WiredValidationErrorComposer = 3766;

    public static int RoomEventComposer { get; internal set; }
}

[PublicAPI]
public enum MessageEvent
{
    BreedPetsMessageEvent = 433,
    CustomizePetWithFurniEvent = 1127,
    GetPetInfoMessageEvent = 3806,
    PetSelectedMessageEvent = 2636,
    RespectPetMessageEvent = 2631,
    ForwardToACompetitionRoomMessageEvent = 1032,
    ForwardToASubmittableRoomMessageEvent = 106,
    ForwardToRandomCompetitionRoomMessageEvent = 1511,
    GetCurrentTimingCodeMessageEvent = 2481,
    GetIsUserPartOfCompetitionMessageEvent = 3351,
    GetSecondsUntilMessageEvent = 463,
    RoomCompetitionInitMessageEvent = 2603,
    SubmitRoomToCompetitionMessageEvent = 2011,
    VoteForRoomMessageEvent = 2346,
    ResetPhoneNumberStateMessageEvent = 2765,
    SetPhoneNumberVerificationStatusMessageEvent = 3207,
    TryPhoneNumberMessageEvent = 2077,
    VerifyCodeMessageEvent = 672,
    CommunityGoalVoteMessageEvent = 3965,
    GetNftCreditsMessageEvent = 320,
    GetSelectedNftWardrobeOutfitMessageEvent = 2862,
    GetSilverMessageEvent = 1990,
    GetUserNftWardrobeMessageEvent = 3695,
    SaveUserNftWardrobeMessageEvent = 613,
    RoomNetworkOpenConnectionMessageEvent = 625,
    GetBotInventoryEvent = 541,
    GetCreditsInfoEvent = 3188,
    GetTalentTrackLevelMessageEvent = 157,
    GetTalentTrackMessageEvent = 905,
    GuideAdvertisementReadMessageEvent = 2998,
    CallForHelpFromForumMessageMessageEvent = 1139,
    CallForHelpFromForumThreadMessageEvent = 3240,
    CallForHelpFromIMMessageEvent = 2619,
    CallForHelpFromPhotoMessageEvent = 3363,
    CallForHelpFromSelfieMessageEvent = 1152,
    CallForHelpMessageEvent = 1425,
    ChatReviewGuideDecidesOnOfferMessageEvent = 604,
    ChatReviewGuideDetachedMessageEvent = 381,
    ChatReviewGuideVoteMessageEvent = 2338,
    ChatReviewSessionCreateMessageEvent = 3625,
    DeletePendingCallsForHelpMessageEvent = 3404,
    GetCfhStatusMessageEvent = 1539,
    GetGuideReportingStatusMessageEvent = 2582,
    GetPendingCallsForHelpMessageEvent = 3833,
    GetQuizQuestionsEvent = 2250,
    GuideSessionCreateMessageEvent = 935,
    GuideSessionFeedbackMessageEvent = 3750,
    GuideSessionGetRequesterRoomMessageEvent = 1783,
    GuideSessionGuideDecidesMessageEvent = 3177,
    GuideSessionInviteRequesterMessageEvent = 3510,
    GuideSessionIsTypingMessageEvent = 91,
    GuideSessionMessageMessageEvent = 701,
    GuideSessionOnDutyUpdateMessageEvent = 1637,
    GuideSessionReportMessageEvent = 3948,
    GuideSessionRequesterCancelsMessageEvent = 3736,
    GuideSessionResolvedMessageEvent = 3657,
    PostQuizAnswersEvent = 726,
    ChangeQueueMessageEvent = 3173,
    OpenFlatConnectionMessageEvent = 2729,
    QuitMessageEvent = 2722,
    BuildersClubPlaceRoomItemMessageEvent = 478,
    BuildersClubPlaceWallItemMessageEvent = 3580,
    BuildersClubQueryFurniCountMessageEvent = 2714,
    GetBonusRareInfoMessageEvent = 1419,
    GetBundleDiscountRulesetEvent = 3154,
    GetCatalogIndexEvent = 3920,
    GetCatalogPageEvent = 1538,
    GetCatalogPageWithEarliestExpiryEvent = 997,
    GetClubGiftMessageEvent = 3210,
    GetClubOffersMessageEvent = 411,
    GetGiftWrappingConfigurationEvent = 2418,
    GetHabboClubExtendOfferMessageEvent = 630,
    GetIsOfferGiftableEvent = 805,
    GetLimitedOfferAppearingNextEvent = 768,
    GetNextTargetedOfferEvent = 1633,
    GetProductOfferEvent = 1326,
    GetRoomAdPurchaseInfoEvent = 1009,
    GetSeasonalCalendarDailyEvent = 268,
    GetSellablePetPalettesEvent = 1227,
    GetSnowWarGameTokensOfferEvent = 3949,
    MarkCatalogNewAdditionsPageOpenedEvent = 193,
    PurchaseBasicMembershipExtensionEvent = 3401,
    PurchaseFromCatalogAsGiftEvent = 644,
    PurchaseFromCatalogEvent = 1852,
    PurchaseRoomAdMessageEvent = 2775,
    PurchaseSnowWarGameTokensOfferEvent = 1376,
    PurchaseTargetedOfferEvent = 3623,
    PurchaseVipMembershipExtensionEvent = 3241,
    RedeemVoucherMessageEvent = 2307,
    RoomAdPurchaseInitiatedEvent = 1614,
    SelectClubGiftEvent = 3915,
    SetTargetedOfferStateEvent = 1229,
    ShopTargetedOfferViewedEvent = 3651,
    NavigatorAddCollapsedCategoryMessageEvent = 494,
    NavigatorAddSavedSearchEvent = 403,
    NavigatorDeleteSavedSearchEvent = 3162,
    NavigatorRemoveCollapsedCategoryMessageEvent = 141,
    NavigatorSetSearchCodeViewModeMessageEvent = 1108,
    NewNavigatorInitEvent = 3032,
    NewNavigatorSearchEvent = 657,
    GetOccupiedTilesMessageEvent = 16,
    GetRoomEntryTileMessageEvent = 2476,
    UpdateFloorPropertiesMessageEvent = 222,
    NewUserExperienceGetGiftsMessageEvent = 1050,
    NewUserExperienceScriptProceedEvent = 3066,
    SelectInitialRoomEvent = 2844,
    GetInterstitialMessageEvent = 3698,
    InterstitialShownMessageEvent = 509,
    CommandBotEvent = 2595,
    GetBotCommandConfigurationDataEvent = 1398,
    GetBadgePointLimitsEvent = 1012,
    GetBadgesEvent = 1047,
    GetIsBadgeRequestFulfilledEvent = 2137,
    RequestABadgeEvent = 520,
    SetActivatedBadgesEvent = 1267,
    ResetUnseenItemIdsEvent = 3082,
    ResetUnseenItemsEvent = 3343,
    AddAdminRightsToMemberMessageEvent = 3727,
    ApproveAllMembershipRequestsMessageEvent = 1622,
    ApproveMembershipRequestMessageEvent = 3478,
    ApproveNameMessageEvent = 737,
    ChangeEmailEvent = 2460,
    CreateGuildMessageEvent = 3692,
    DeactivateGuildMessageEvent = 195,
    DeselectFavouriteHabboGroupMessageEvent = 2131,
    GetEmailStatusEvent = 3596,
    GetExtendedProfileByNameMessageEvent = 1037,
    GetExtendedProfileMessageEvent = 2845,
    GetGuildCreationInfoMessageEvent = 386,
    GetGuildEditInfoMessageEvent = 3118,
    GetGuildEditorDataMessageEvent = 2663,
    GetGuildMembershipsMessageEvent = 813,
    GetGuildMembersMessageEvent = 1294,
    GetHabboGroupBadgesMessageEvent = 2317,
    GetHabboGroupDetailsMessageEvent = 1630,
    GetIgnoredUsersMessageEvent = 1601,
    GetMemberGuildItemCountMessageEvent = 1434,
    GetMOTDMessageEvent = 1441,
    GetRelationshipStatusInfoMessageEvent = 1015,
    GetSelectedBadgesMessageEvent = 68,
    GetUserNftChatStylesMessageEvent = 3492,
    GiveStarGemToUserMessageEvent = 1833,
    IgnoreUserMessageEvent = 2249,
    JoinHabboGroupMessageEvent = 51,
    KickMemberMessageEvent = 3340,
    RejectMembershipRequestMessageEvent = 1046,
    RemoveAdminRightsFromMemberMessageEvent = 2162,
    ScrGetKickbackInfoMessageEvent = 2496,
    ScrGetUserInfoMessageEvent = 1909,
    SelectFavouriteHabboGroupMessageEvent = 3566,
    UnblockGroupMemberMessageEvent = 3357,
    UnignoreUserMessageEvent = 3881,
    UpdateGuildBadgeMessageEvent = 3959,
    UpdateGuildColorsMessageEvent = 3933,
    UpdateGuildIdentityMessageEvent = 1897,
    UpdateGuildSettingsMessageEvent = 1914,
    CraftEvent = 2681,
    CraftSecretEvent = 526,
    GetCraftableProductsEvent = 1956,
    GetCraftingRecipeEvent = 459,
    GetCraftingRecipesAvailableEvent = 712,
    CloseIssueDefaultActionMessageEvent = 3172,
    CloseIssuesMessageEvent = 421,
    DefaultSanctionMessageEvent = 3706,
    GetCfhChatlogMessageEvent = 3282,
    GetModeratorRoomInfoMessageEvent = 3747,
    GetModeratorUserInfoMessageEvent = 3785,
    GetRoomChatlogMessageEvent = 2007,
    GetRoomVisitsMessageEvent = 1154,
    GetUserChatlogMessageEvent = 2841,
    ModAlertMessageEvent = 2513,
    ModBanMessageEvent = 1176,
    ModerateRoomMessageEvent = 3852,
    ModeratorActionMessageEvent = 864,
    ModKickMessageEvent = 3335,
    ModMessageMessageEvent = 1560,
    ModMuteMessageEvent = 1469,
    ModToolPreferencesEvent = 2374,
    ModToolSanctionEvent = 852,
    ModTradingLockMessageEvent = 1883,
    PickIssuesMessageEvent = 3919,
    ReleaseIssuesMessageEvent = 1565,
    ClientHelloMessageEvent = 4000,
    CompleteDiffieHandshakeMessageEvent = 2616,
    DisconnectMessageEvent = 1113,
    InfoRetrieveMessageEvent = 245,
    InitDiffieHandshakeMessageEvent = 586,
    PongMessageEvent = 2331,
    SSOTicketMessageEvent = 53,
    UniqueIDMessageEvent = 1390,
    VersionCheckMessageEvent = 2602,
    AcceptQuestMessageEvent = 2708,
    ActivateQuestMessageEvent = 3632,
    CancelQuestMessageEvent = 3171,
    FriendRequestQuestCompleteMessageEvent = 1807,
    GetCommunityGoalHallOfFameMessageEvent = 1704,
    GetCommunityGoalProgressMessageEvent = 124,
    GetConcurrentUsersGoalProgressMessageEvent = 1116,
    GetConcurrentUsersRewardMessageEvent = 2068,
    GetDailyQuestMessageEvent = 17,
    GetQuestsMessageEvent = 2370,
    GetSeasonalQuestsOnlyMessageEvent = 2325,
    OpenQuestTrackerMessageEvent = 2718,
    RejectQuestMessageEvent = 573,
    StartCampaignMessageEvent = 754,
    GetHotLooksMessageEvent = 872,
    ClickFurniMessageEvent = 757,
    CompostPlantMessageEvent = 856,
    GetFurnitureAliasesMessageEvent = 2064,
    GetHeightMapMessageEvent = 1935,
    GetItemDataMessageEvent = 2327,
    GetPetCommandsMessageEvent = 2534,
    GiveSupplementToPetMessageEvent = 2270,
    HarvestPetMessageEvent = 1297,
    MountPetMessageEvent = 2877,
    MoveAvatarMessageEvent = 2363,
    MoveObjectMessageEvent = 2351,
    MovePetMessageEvent = 2899,
    MoveWallItemMessageEvent = 43,
    PickupObjectMessageEvent = 2085,
    PlaceBotMessageEvent = 180,
    PlaceObjectMessageEvent = 171,
    PlacePetMessageEvent = 2339,
    RemoveBotFromFlatMessageEvent = 3758,
    RemoveItemMessageEvent = 2639,
    RemovePetFromFlatMessageEvent = 2302,
    RemoveSaddleFromPetMessageEvent = 2293,
    SetClothingChangeDataMessageEvent = 1923,
    SetItemDataMessageEvent = 1171,
    SetObjectDataMessageEvent = 885,
    TogglePetBreedingPermissionMessageEvent = 2972,
    TogglePetRidingPermissionMessageEvent = 3575,
    UseFurnitureMessageEvent = 147,
    UseWallItemMessageEvent = 843,
    CreditVaultStatusMessageEvent = 758,
    IncomeRewardClaimMessageEvent = 1931,
    IncomeRewardStatusMessageEvent = 2477,
    WithdrawCreditVaultMessageEvent = 1355,
    OpenCampaignCalendarDoorAsStaffEvent = 3280,
    OpenCampaignCalendarDoorEvent = 3165,
    AcceptTradingEvent = 1746,
    AddItemsToTradeEvent = 2839,
    AddItemToTradeEvent = 3472,
    CloseTradingEvent = 1781,
    ConfirmAcceptTradingEvent = 1918,
    ConfirmDeclineTradingEvent = 1626,
    OpenTradingEvent = 3040,
    RemoveItemFromTradeEvent = 1709,
    SilverFeeMessageEvent = 1575,
    UnacceptTradingEvent = 1779,
    UpdateFigureDataMessageEvent = 483,
    AvatarExpressionMessageEvent = 3794,
    ChangeMottoMessageEvent = 2404,
    ChangePostureMessageEvent = 917,
    CustomizeAvatarWithFurniMessageEvent = 920,
    DanceMessageEvent = 2185,
    DropCarryItemMessageEvent = 616,
    LookToMessageEvent = 300,
    PassCarryItemMessageEvent = 599,
    PassCarryItemToPetMessageEvent = 1076,
    SignMessageEvent = 311,
    Game2CheckGameDirectoryStatusMessageEvent = 700,
    Game2GetAccountGameStatusMessageEvent = 3967,
    Game2LeaveGameMessageEvent = 3271,
    Game2QuickJoinGameMessageEvent = 1005,
    Game2StartSnowWarMessageEvent = 2703,
    GetForumsListMessageEvent = 506,
    GetForumStatsMessageEvent = 3523,
    GetMessagesMessageEvent = 3507,
    GetThreadMessageEvent = 2611,
    GetThreadsMessageEvent = 1898,
    GetUnreadForumsCountMessageEvent = 2798,
    ModerateMessageMessageEvent = 3274,
    ModerateThreadMessageEvent = 1976,
    PostMessageMessageEvent = 2253,
    UpdateForumReadMarkerMessageEvent = 2837,
    UpdateForumSettingsMessageEvent = 127,
    UpdateThreadMessageEvent = 2624,
    AddJukeboxDiskEvent = 1249,
    GetJukeboxPlayListMessageEvent = 2182,
    GetNowPlayingMessageEvent = 1753,
    GetOfficialSongIdMessageEvent = 1952,
    GetSongInfoMessageEvent = 2593,
    GetSoundMachinePlayListMessageEvent = 1477,
    GetSoundSettingsEvent = 3130,
    GetUserSongDisksMessageEvent = 1947,
    RemoveJukeboxDiskEvent = 3484,
    ChangeUserNameInRoomMessageEvent = 306,
    ChangeUserNameMessageEvent = 3175,
    CheckUserNameMessageEvent = 2109,
    GetWardrobeMessageEvent = 772,
    SaveWardrobeOutfitMessageEvent = 976,
    BuyMarketplaceOfferMessageEvent = 2305,
    BuyMarketplaceTokensMessageEvent = 2760,
    CancelMarketplaceOfferMessageEvent = 3809,
    GetMarketplaceCanMakeOfferMessageEvent = 2123,
    GetMarketplaceConfigurationMessageEvent = 1104,
    GetMarketplaceItemStatsEvent = 1617,
    GetMarketplaceOffersMessageEvent = 1814,
    GetMarketplaceOwnOffersMessageEvent = 2749,
    MakeOfferMessageEvent = 3768,
    RedeemMarketplaceOfferCreditsMessageEvent = 1417,
    GetAchievementsEvent = 2558,
    AddSpamWallPostItMessageEvent = 683,
    ControlYoutubeDisplayPlaybackMessageEvent = 2847,
    CreditFurniRedeemMessageEvent = 1554,
    DiceOffMessageEvent = 505,
    EnterOneWayDoorMessageEvent = 1843,
    ExtendRentOrBuyoutFurniMessageEvent = 2666,
    ExtendRentOrBuyoutStripItemMessageEvent = 1881,
    GetGuildFurniContextMenuInfoMessageEvent = 3007,
    GetRentOrBuyoutOfferMessageEvent = 2114,
    GetYoutubeDisplayStatusMessageEvent = 2362,
    OpenMysteryTrophyMessageEvent = 1880,
    OpenPetPackageMessageEvent = 20,
    PlacePostItMessageEvent = 1865,
    PresentOpenMessageEvent = 2269,
    RentableSpaceCancelRentMessageEvent = 2321,
    RentableSpaceRentMessageEvent = 521,
    RentableSpaceStatusMessageEvent = 1330,
    RoomDimmerChangeStateMessageEvent = 661,
    RoomDimmerGetPresetsMessageEvent = 842,
    RoomDimmerSavePresetMessageEvent = 1459,
    SetAreaHideDataEvent = 3186,
    SetCustomStackingHeightEvent = 1670,
    SetMannequinFigureEvent = 2244,
    SetMannequinNameEvent = 2809,
    SetRandomStateMessageEvent = 626,
    SetRoomBackgroundColorDataEvent = 2197,
    SetYoutubeDisplayPlaylistMessageEvent = 3074,
    SpinWheelOfFortuneMessageEvent = 3373,
    ThrowDiceMessageEvent = 2348,
    GetResolutionAchievementsMessageEvent = 1313,
    CancelPetBreedingEvent = 1616,
    ConfirmPetBreedingEvent = 3046,
    GetPetInventoryEvent = 1967,
    EventLogMessageEvent = 2297,
    LagWarningReportMessageEvent = 2304,
    LatencyPingReportMessageEvent = 3835,
    LatencyPingRequestMessageEvent = 3638,
    PerformanceLogMessageEvent = 747,
    FriendFurniConfirmLockMessageEvent = 2473,
    Game2MakeSnowballMessageEvent = 583,
    Game2RequestFullStatusUpdateMessageEvent = 2200,
    Game2SetUserMoveTargetMessageEvent = 2470,
    Game2ThrowSnowballAtHumanMessageEvent = 740,
    Game2ThrowSnowballAtPositionMessageEvent = 1739,
    AvatarEffectActivatedEvent = 90,
    AvatarEffectSelectedEvent = 1393,
    AddFavouriteRoomMessageEvent = 915,
    CancelEventMessageEvent = 1684,
    CanCreateRoomMessageEvent = 2897,
    CompetitionRoomsSearchMessageEvent = 3578,
    ConvertGlobalRoomIdMessageEvent = 2889,
    CreateFlatMessageEvent = 3526,
    DeleteFavouriteRoomMessageEvent = 79,
    EditEventMessageEvent = 692,
    ForwardToARandomPromotedRoomMessageEvent = 1521,
    ForwardToSomeRoomMessageEvent = 524,
    GetGuestRoomMessageEvent = 1561,
    GetOfficialRoomsMessageEvent = 2089,
    GetPopularRoomTagsMessageEvent = 3900,
    GetUserEventCatsMessageEvent = 1679,
    GetUserFlatCatsMessageEvent = 315,
    GuildBaseSearchMessageEvent = 2806,
    MyFavouriteRoomsSearchMessageEvent = 2673,
    MyFrequentRoomHistorySearchMessageEvent = 3783,
    MyFriendsRoomsSearchMessageEvent = 2171,
    MyGuildBasesSearchMessageEvent = 3530,
    MyRecommendedRoomsMessageEvent = 1686,
    MyRoomHistorySearchMessageEvent = 3392,
    MyRoomRightsSearchMessageEvent = 283,
    MyRoomsSearchMessageEvent = 3540,
    PopularRoomsSearchMessageEvent = 324,
    RateFlatMessageEvent = 2080,
    RemoveOwnRoomRightsRoomMessageEvent = 1189,
    RoomAdEventTabAdClickedEvent = 1199,
    RoomAdEventTabViewedEvent = 1472,
    RoomAdSearchMessageEvent = 1526,
    RoomsWhereMyFriendsAreSearchMessageEvent = 1105,
    RoomsWithHighestScoreSearchMessageEvent = 1890,
    RoomTextSearchMessageEvent = 3236,
    SetRoomSessionTagsMessageEvent = 790,
    ToggleStaffPickMessageEvent = 1210,
    UpdateHomeRoomMessageEvent = 2188,
    GetCollectibleMintableItemTypesMessageEvent = 3487,
    GetCollectibleMintingEnabledMessageEvent = 850,
    GetCollectibleMintTokensMessageEvent = 3814,
    GetCollectibleWalletAddressesMessageEvent = 250,
    GetCollectorScoreMessageEvent = 1948,
    GetMintTokenOffersMessageEvent = 355,
    GetNftCollectionsMessageEvent = 3560,
    GetNftTransferFeeMessageEvent = 2020,
    MintItemMessageEvent = 2205,
    NftCollectiblesClaimBonusItemMessageEvent = 1598,
    NftCollectiblesClaimRewardItemMessageEvent = 1487,
    NftTransferAssetsMessageEvent = 1430,
    PurchaseMintTokenMessageEvent = 3534,
    PeerUsersClassificationMessageEvent = 663,
    RoomUsersClassificationMessageEvent = 2549,
    MysteryBoxWaitingCanceledMessageEvent = 3216,
    AmbassadorAlertMessageEvent = 3914,
    AssignRightsMessageEvent = 161,
    BanUserWithDurationMessageEvent = 1061,
    KickUserMessageEvent = 2046,
    LetUserInMessageEvent = 3962,
    MuteAllInRoomEvent = 1732,
    MuteUserMessageEvent = 296,
    RemoveAllRightsMessageEvent = 1951,
    RemoveRightsMessageEvent = 108,
    UnbanUserFromRoomMessageEvent = 3013,
    UnmuteUserMessageEvent = 1251,
    PollAnswerEvent = 833,
    PollRejectEvent = 2168,
    PollStartEvent = 1049,
    DeleteRoomMessageEvent = 3760,
    GetBannedUsersFromRoomMessageEvent = 3681,
    GetCustomRoomFilterMessageEvent = 1200,
    GetFlatControllersMessageEvent = 2141,
    GetRoomSettingsMessageEvent = 584,
    SaveRoomSettingsMessageEvent = 966,
    UpdateRoomCategoryAndTradeSettingsEvent = 201,
    UpdateRoomFilterMessageEvent = 1847,
    RequestFurniInventoryEveGetGuestRoomMessagent = 3181,
    RequestFurniInventoryWhenNotInRoomEvent = 3468,
    RequestRoomPropertySet = 2982,
    Game2GetFriendsLeaderboardEvent = 1959,
    Game2GetTotalGroupLeaderboardEvent = 1360,
    Game2GetTotalLeaderboardEvent = 3654,
    Game2GetWeeklyFriendsLeaderboardEvent = 3734,
    Game2GetWeeklyGroupLeaderboardEvent = 3312,
    Game2GetWeeklyLeaderboardEvent = 2049,
    CancelTypingMessageEvent = 3878,
    ChatMessageEvent = 2057,
    ShoutMessageEvent = 380,
    StartTypingMessageEvent = 2678,
    WhisperMessageEvent = 2065,
    WiredClearErrorLogsMessageEvent = 2087,
    WiredGetAllVariableHoldersMessageEvent = 3266,
    WiredGetAllVariablesDiffsMessageEvent = 1201,
    WiredGetAllVariablesHashMessageEvent = 94,
    WiredGetErrorLogsMessageEvent = 3600,
    WiredGetRoomSettingsMessageEvent = 2959,
    WiredGetRoomStatsMessageEvent = 3452,
    WiredGetVariablesForObjectMessageEvent = 3288,
    WiredSetObjectVariableValueMessageEvent = 2863,
    WiredSetPreferencesMessageEvent = 3975,
    WiredSetRoomSettingsMessageEvent = 3477,
    AcceptFriendMessageEvent = 76,
    DeclineFriendMessageEvent = 3308,
    FindNewFriendsMessageEvent = 3473,
    FollowFriendMessageEvent = 2446,
    FriendListUpdateMessageEvent = 1399,
    GetFriendRequestsMessageEvent = 406,
    GetMessengerHistoryEvent = 799,
    HabboSearchMessageEvent = 1378,
    MessengerInitMessageEvent = 472,
    RemoveFriendMessageEvent = 417,
    RequestFriendMessageEvent = 1645,
    SendMsgMessageEvent = 2800,
    SendRoomInviteMessageEvent = 366,
    SetRelationshipStatusMessageEvent = 1666,
    VisitUserMessageEvent = 2578,
    SetChatPreferencesMessageEvent = 1179,
    SetChatStylePreferenceEvent = 766,
    SetIgnoreRoomInvitesMessageEvent = 3746,
    SetNewNavigatorWindowPreferencesMessageEvent = 1912,
    SetRoomCameraPreferencesMessageEvent = 874,
    SetSoundSettingsEvent = 264,
    SetUIFlagsMessageEvent = 2209,
    Game2ExitGameMessageEvent = 3755,
    Game2GameChatMessageEvent = 2265,
    Game2LoadStageReadyMessageEvent = 1373,
    Game2PlayAgainMessageEvent = 3041,
    PhotoCompetitionMessageEvent = 102,
    PublishPhotoMessageEvent = 1394,
    PurchasePhotoMessageEvent = 795,
    RenderRoomMessageEvent = 2443,
    RenderRoomThumbnailMessageEvent = 1409,
    RequestCameraConfigurationMessageEvent = 1503,
    GetPromoArticlesMessageEvent = 3519,
    ApplySnapshotMessageEvent = 2508,
    OpenMessageEvent = 2428,
    UpdateActionMessageEvent = 1039,
    UpdateAddonMessageEvent = 954,
    UpdateConditionMessageEvent = 2641,
    UpdateSelectorMessageEvent = 2159,
    UpdateTriggerMessageEvent = 2901,
    UpdateVariableMessageEvent = 372
}