using JetBrains.Annotations;

namespace Turbo.WIN63202506020918587581630;

public static class MessageComposer
{
    public const int CantConnectMessageComposer = 3751;
    public const int CloseConnectionMessageComposer = 2089;
    public const int FlatAccessibleMessageComposer = 3619;
    public const int GamePlayerValueMessageComposer = 3648;
    public const int HanditemConfigurationMessageComposer = 2010;
    public const int OpenConnectionMessageComposer = 2297;
    public const int RoomForwardMessageComposer = 22;
    public const int RoomQueueStatusMessageComposer = 3128;
    public const int RoomReadyMessageComposer = 480;
    public const int YouAreNotSpectatorMessageComposer = 497;
    public const int YouArePlayingGameMessageComposer = 1477;
    public const int YouAreSpectatorMessageComposer = 2904;
    public const int BotCommandConfigurationComposer = 1820;
    public const int BotErrorComposer = 2793;
    public const int BotForceOpenContextMenuComposer = 384;
    public const int BotSkillListUpdateComposer = 2454;
    public const int AvailabilityStatusMessageComposer = 759;
    public const int InfoHotelClosedMessageComposer = 1979;
    public const int InfoHotelClosingMessageComposer = 3242;
    public const int LoginFailedHotelClosedMessageComposer = 2910;
    public const int MaintenanceStatusMessageComposer = 2271;
    public const int NewUserExperienceGiftOfferComposer = 1067;
    public const int NewUserExperienceNotCompleteComposer = 2773;
    public const int SelectInitialRoomComposer = 1406;
    public const int JukeboxPlayListFullMessageComposer = 903;
    public const int JukeboxSongDisksMessageComposer = 2196;
    public const int NowPlayingMessageComposer = 3150;
    public const int OfficialSongIdMessageComposer = 2372;
    public const int PlayListMessageComposer = 1023;
    public const int PlayListSongAddedMessageComposer = 1484;
    public const int TraxSongInfoMessageComposer = 3836;
    public const int UserSongDisksInventoryMessageComposer = 2232;
    public const int AchievementComposer = 2204;
    public const int AchievementsComposer = 2345;
    public const int AchievementsScoreComposer = 1695;
    public const int CampaignCalendarDataMessageComposer = 2278;
    public const int CampaignCalendarDoorOpenedMessageComposer = 2949;
    public const int BonusRareInfoMessageComposer = 3130;
    public const int BuildersClubFurniCountMessageComposer = 1022;
    public const int BuildersClubSubscriptionStatusMessageComposer = 754;
    public const int BundleDiscountRulesetMessageComposer = 1256;
    public const int CatalogIndexMessageComposer = 1040;
    public const int CatalogPageMessageComposer = 2175;
    public const int CatalogPageWithEarliestExpiryMessageComposer = 2640;
    public const int CatalogPublishedMessageComposer = 1759;
    public const int ClubGiftInfoComposer = 2462;
    public const int ClubGiftSelectedComposer = 2753;
    public const int GiftReceiverNotFoundComposer = 476;
    public const int GiftWrappingConfigurationComposer = 1956;
    public const int HabboClubExtendOfferMessageComposer = 222;
    public const int HabboClubOffersMessageComposer = 1919;
    public const int LimitedEditionSoldOutComposer = 3779;
    public const int LimitedOfferAppearingNextMessageComposer = 2975;
    public const int NotEnoughBalanceMessageComposer = 3775;
    public const int ProductOfferComposer = 2817;
    public const int PurchaseErrorMessageComposer = 461;
    public const int PurchaseNotAllowedMessageComposer = 3938;
    public const int PurchaseOKMessageComposer = 2107;
    public const int RoomAdPurchaseInfoComposer = 3452;
    public const int SeasonalCalendarDailyOfferMessageComposer = 1905;
    public const int SellablePetPalettesMessageComposer = 952;
    public const int SnowWarGameTokensMessageComposer = 3736;
    public const int TargetedOfferComposer = 2602;
    public const int TargetedOfferNotFoundComposer = 3088;
    public const int VoucherRedeemErrorMessageComposer = 2638;
    public const int VoucherRedeemOkMessageComposer = 3642;
    public const int CallForHelpDisabledNotifyMessageComposer = 1258;
    public const int CallForHelpPendingCallsDeletedMessageComposer = 3769;
    public const int CallForHelpPendingCallsMessageComposer = 3292;
    public const int CallForHelpReplyMessageComposer = 3817;
    public const int CallForHelpResultMessageComposer = 3437;
    public const int ChatReviewSessionDetachedMessageComposer = 3860;
    public const int ChatReviewSessionOfferedToGuideMessageComposer = 1430;
    public const int ChatReviewSessionResultsMessageComposer = 1270;
    public const int ChatReviewSessionStartedMessageComposer = 851;
    public const int ChatReviewSessionVotingStatusMessageComposer = 1192;
    public const int GuideOnDutyStatusMessageComposer = 2320;
    public const int GuideReportingStatusMessageComposer = 132;
    public const int GuideSessionAttachedMessageComposer = 3908;
    public const int GuideSessionDetachedMessageComposer = 2140;
    public const int GuideSessionEndedMessageComposer = 2363;
    public const int GuideSessionErrorMessageComposer = 2702;
    public const int GuideSessionInvitedToGuideRoomMessageComposer = 3167;
    public const int GuideSessionMessageMessageComposer = 774;
    public const int GuideSessionPartnerIsTypingMessageComposer = 2546;
    public const int GuideSessionRequesterRoomMessageComposer = 500;
    public const int GuideSessionStartedMessageComposer = 42;
    public const int GuideTicketCreationResultMessageComposer = 891;
    public const int GuideTicketResolutionMessageComposer = 3767;
    public const int IssueCloseNotificationMessageComposer = 1942;
    public const int QuizDataMessageComposer = 2688;
    public const int QuizResultsMessageComposer = 1737;
    public const int Game2ArenaEnteredMessageComposer = 2082;
    public const int Game2EnterArenaFailedMessageComposer = 3163;
    public const int Game2EnterArenaMessageComposer = 2228;
    public const int Game2GameChatFromPlayerMessageComposer = 1384;
    public const int Game2GameEndingMessageComposer = 1822;
    public const int Game2GameRejoinMessageComposer = 3568;
    public const int Game2PlayerExitedGameArenaMessageComposer = 533;
    public const int Game2PlayerRematchesMessageComposer = 1975;
    public const int Game2StageEndingMessageComposer = 295;
    public const int Game2StageLoadMessageComposer = 1175;
    public const int Game2StageRunningMessageComposer = 684;
    public const int Game2StageStartingMessageComposer = 1428;
    public const int Game2StageStillLoadingMessageComposer = 3170;
    public const int AreaHideMessageComposer = 1011;
    public const int CustomStackingHeightUpdateMessageComposer = 3725;
    public const int CustomUserNotificationMessageComposer = 3160;
    public const int DiceValueMessageComposer = 1379;
    public const int FurniRentOrBuyoutOfferMessageComposer = 624;
    public const int GuildFurniContextMenuInfoMessageComposer = 3964;
    public const int OneWayDoorStatusMessageComposer = 1854;
    public const int OpenPetPackageRequestedMessageComposer = 1983;
    public const int OpenPetPackageResultMessageComposer = 1394;
    public const int PresentOpenedMessageComposer = 1514;
    public const int RentableSpaceRentFailedMessageComposer = 3901;
    public const int RentableSpaceRentOkMessageComposer = 735;
    public const int RentableSpaceStatusMessageComposer = 3402;
    public const int RequestSpamWallPostItMessageComposer = 1075;
    public const int RoomDimmerPresetsMessageComposer = 748;
    public const int RoomMessageNotificationMessageComposer = 1735;
    public const int YoutubeControlVideoMessageComposer = 2236;
    public const int YoutubeDisplayPlaylistsMessageComposer = 2939;
    public const int YoutubeDisplayVideoMessageComposer = 2031;
    public const int ErrorReportComposer = 3868;
    public const int TradeOpenFailedComposer = 1692;
    public const int TradeSilverFeeMessageComposer = 2820;
    public const int TradeSilverSetMessageComposer = 1575;
    public const int TradingAcceptComposer = 1901;
    public const int TradingCloseComposer = 2906;
    public const int TradingCompletedComposer = 3521;
    public const int TradingConfirmationComposer = 819;
    public const int TradingItemListComposer = 973;
    public const int TradingNotOpenComposer = 3828;
    public const int TradingOpenComposer = 1997;
    public const int TradingOtherNotAllowedComposer = 3435;
    public const int TradingYouAreNotAllowedComposer = 2427;
    public const int MarketplaceBuyOfferResultComposer = 2870;
    public const int MarketplaceCancelOfferResultComposer = 264;
    public const int MarketplaceCanMakeOfferResult = 1060;
    public const int MarketplaceConfigurationComposer = 3669;
    public const int MarketplaceItemStatsComposer = 699;
    public const int MarketplaceMakeOfferResult = 1097;
    public const int MarketPlaceOffersComposer = 3320;
    public const int MarketPlaceOwnOffersComposer = 2207;
    public const int CitizenshipVipOfferPromoEnabledComposer = 371;
    public const int PerkAllowancesMessageComposer = 1734;
    public const int RoomEntryTileMessageComposer = 2916;
    public const int RoomOccupiedTilesMessageComposer = 253;
    public const int HotLooksMessageComposer = 457;
    public const int FriendFurniCancelLockMessageComposer = 3554;
    public const int FriendFurniOtherLockConfirmedMessageComposer = 712;
    public const int FriendFurniStartConfirmationMessageComposer = 2758;
    public const int CreditBalanceComposer = 2862;
    public const int AvatarEffectMessageComposer = 1937;
    public const int CarryObjectMessageComposer = 2851;
    public const int DanceMessageComposer = 1123;
    public const int ExpressionMessageComposer = 103;
    public const int SleepMessageComposer = 3311;
    public const int UseObjectMessageComposer = 1457;
    public const int Game2AccountGameStatusMessageComposer = 1791;
    public const int Game2GameCancelledMessageComposer = 2106;
    public const int Game2GameCreatedMessageComposer = 1712;
    public const int Game2GameDirectoryStatusMessageComposer = 1007;
    public const int Game2GameLongDataMessageComposer = 1250;
    public const int Game2GameStartedMessageComposer = 1035;
    public const int Game2InArenaQueueMessageComposer = 472;
    public const int Game2JoiningGameFailedMessageComposer = 1996;
    public const int Game2StartCounterMessageComposer = 2835;
    public const int Game2StartingGameFailedMessageComposer = 1078;
    public const int Game2StopCounterMessageComposer = 972;
    public const int Game2UserBlockedMessageComposer = 3027;
    public const int Game2UserJoinedGameMessageComposer = 1029;
    public const int Game2UserLeftGameMessageComposer = 3975;
    public const int ChangeUserNameResultMessageComposer = 3700;
    public const int CheckUserNameResultMessageComposer = 1340;
    public const int FigureUpdateComposer = 1705;
    public const int WardrobeMessageComposer = 3046;
    public const int CollectableMintableItemTypesMessageComposer = 199;
    public const int CollectibleMintableItemResultMessageComposer = 2819;
    public const int CollectibleMintingEnabledMessageComposer = 406;
    public const int CollectibleMintTokenCountMessageComposer = 3097;
    public const int CollectibleMintTokenOffersMessageComposer = 102;
    public const int CollectibleWalletAddressesMessageComposer = 1016;
    public const int EmeraldBalanceMessageComposer = 2473;
    public const int NftBonusItemClaimResultMessageComposer = 3570;
    public const int NftCollectionsMessageComposer = 1557;
    public const int NftCollectionsScoreMessageComposer = 1281;
    public const int NftRewardItemClaimResultMessageComposer = 905;
    public const int NftTransferAssetsResultMessageComposer = 492;
    public const int NftTransferFeeMessageComposer = 262;
    public const int SilverBalanceMessageComposer = 2367;
    public const int AcceptFriendResultComposer = 1084;
    public const int ConsoleMessageHistoryComposer = 3618;
    public const int FindFriendsProcessResultComposer = 1683;
    public const int FollowFriendFailedComposer = 2366;
    public const int FriendListFragmentMessageComposer = 2695;
    public const int FriendListUpdateComposer = 1725;
    public const int FriendNotificationComposer = 933;
    public const int FriendRequestsComposer = 2452;
    public const int HabboSearchResultComposer = 1841;
    public const int InstantMessageErrorComposer = 3837;
    public const int MessengerErrorComposer = 1115;
    public const int MessengerInitComposer = 3785;
    public const int MiniMailNewMessageComposer = 2930;
    public const int MiniMailUnreadCountComposer = 645;
    public const int NewConsoleMessageComposer = 3821;
    public const int NewFriendRequestComposer = 2799;
    public const int RoomInviteErrorComposer = 872;
    public const int RoomInviteComposer = 3505;
    public const int InterstitialMessageComposer = 2932;
    public const int RoomAdErrorComposer = 3427;
    public const int ForumDataMessageComposer = 2542;
    public const int ForumsListMessageComposer = 907;
    public const int ForumThreadsMessageComposer = 2488;
    public const int PostMessageMessageComposer = 3922;
    public const int PostThreadMessageComposer = 1488;
    public const int ThreadMessagesMessageComposer = 236;
    public const int UnreadForumsCountMessageComposer = 114;
    public const int UpdateMessageMessageComposer = 2028;
    public const int UpdateThreadMessageComposer = 1918;
    public const int CreditVaultStatusMessageComposer = 2374;
    public const int IncomeRewardClaimResponseMessageComposer = 136;
    public const int IncomeRewardStatusMessageComposer = 1275;
    public const int BotAddedToInventoryComposer = 81;
    public const int BotInventoryComposer = 3612;
    public const int BotRemovedFromInventoryComposer = 171;
    public const int BadgePointLimitsComposer = 256;
    public const int BadgeReceivedComposer = 2788;
    public const int BadgesComposer = 2510;
    public const int IsBadgeRequestFulfilledComposer = 3114;
    public const int NavigatorCollapsedCategoriesMessageComposer = 2664;
    public const int NavigatorLiftedRoomsComposer = 1632;
    public const int NavigatorMetaDataComposer = 2525;
    public const int NavigatorSavedSearchesComposer = 629;
    public const int NavigatorSearchResultBlocksComposer = 3234;
    public const int NewNavigatorPreferencesComposer = 1959;
    public const int BannedUsersFromRoomComposer = 3095;
    public const int FlatControllerAddedComposer = 2444;
    public const int FlatControllerRemovedComposer = 3087;
    public const int FlatControllersComposer = 1677;
    public const int MuteAllInRoomComposer = 2496;
    public const int NoSuchFlatComposer = 3433;
    public const int RoomSettingsDataComposer = 986;
    public const int RoomSettingsErrorComposer = 374;
    public const int RoomSettingsSavedComposer = 2313;
    public const int RoomSettingsSaveErrorComposer = 1464;
    public const int ShowEnforceRoomCategoryDialogComposer = 3062;
    public const int UserUnbannedFromRoomComposer = 2707;
    public const int PollContentsComposer = 3920;
    public const int PollErrorComposer = 3189;
    public const int PollOfferComposer = 3023;
    public const int QuestionAnsweredComposer = 1994;
    public const int QuestionComposer = 960;
    public const int QuestionFinishedComposer = 3301;
    public const int Game2FullGameStatusMessageComposer = 2155;
    public const int Game2GameStatusMessageComposer = 2146;
    public const int CompetitionEntrySubmitResultMessageComposer = 3562;
    public const int CompetitionVotingInfoMessageComposer = 853;
    public const int CurrentTimingCodeMessageComposer = 3567;
    public const int IsUserPartOfCompetitionMessageComposer = 176;
    public const int NoOwnedRoomsAlertMessageComposer = 3665;
    public const int SecondsUntilMessageComposer = 2404;
    public const int CfhChatlogComposer = 1330;
    public const int IssueDeletedMessageComposer = 3756;
    public const int IssueInfoMessageComposer = 2696;
    public const int IssuePickFailedMessageComposer = 586;
    public const int ModeratorActionResultMessageComposer = 731;
    public const int ModeratorCautionComposer = 1955;
    public const int ModeratorInitMessageComposer = 569;
    public const int ModeratorMessageComposer = 611;
    public const int ModeratorRoomInfoComposer = 2582;
    public const int ModeratorToolPreferencesComposer = 1252;
    public const int ModeratorUserInfoComposer = 2459;
    public const int RoomChatlogComposer = 2744;
    public const int RoomVisitsComposer = 585;
    public const int UserBannedMessageComposer = 3265;
    public const int UserChatlogComposer = 2917;
    public const int CraftableProductsMessageComposer = 1309;
    public const int CraftingRecipeMessageComposer = 2403;
    public const int CraftingRecipesAvailableMessageComposer = 2165;
    public const int CraftingResultMessageComposer = 434;
    public const int ChatMessageComposer = 1509;
    public const int FloodControlMessageComposer = 426;
    public const int RemainingMutePeriodComposer = 2692;
    public const int RoomChatSettingsMessageComposer = 540;
    public const int RoomFilterSettingsMessageComposer = 1673;
    public const int ShoutMessageComposer = 3413;
    public const int UserTypingMessageComposer = 669;
    public const int WhisperMessageComposer = 2230;
    public const int ConfirmBreedingRequestComposer = 3942;
    public const int ConfirmBreedingResultComposer = 1057;
    public const int GoToBreedingNestFailureComposer = 416;
    public const int NestBreedingSuccessComposer = 1047;
    public const int PetAddedToInventoryComposer = 2353;
    public const int PetBreedingComposer = 3992;
    public const int PetInventoryComposer = 3384;
    public const int PetReceivedMessageComposer = 454;
    public const int PetRemovedFromInventoryComposer = 1325;
    public const int CameraPublishStatusMessageComposer = 2689;
    public const int CameraPurchaseOKMessageComposer = 1167;
    public const int CameraStorageUrlMessageComposer = 3054;
    public const int CompetitionStatusMessageComposer = 720;
    public const int InitCameraMessageComposer = 923;
    public const int ThumbnailStatusMessageComposer = 99;
    public const int CancelMysteryBoxWaitMessageComposer = 173;
    public const int GotMysteryBoxPrizeMessageComposer = 2677;
    public const int MysteryBoxKeysMessageComposer = 1786;
    public const int ShowMysteryBoxWaitMessageComposer = 3262;
    public const int WiredAllVariableHoldersComposer = 1971;
    public const int WiredAllVariablesDiffsComposer = 3778;
    public const int WiredAllVariablesHashComposer = 3495;
    public const int WiredErrorLogsComposer = 41;
    public const int WiredMenuErrorComposer = 764;
    public const int WiredPermissionsComposer = 3651;
    public const int WiredRoomSettingsComposer = 2183;
    public const int WiredRoomStatsComposer = 17;
    public const int WiredVariablesForObjectComposer = 3468;
    public const int AuthenticationOKMessageComposer = 388;
    public const int CompleteDiffieHandshakeComposer = 217;
    public const int DisconnectReasonComposer = 4000;
    public const int GenericErrorComposer = 1045;
    public const int IdentityAccountsComposer = 1726;
    public const int InitDiffieHandshakeComposer = 3845;
    public const int IsFirstLoginOfDayComposer = 2989;
    public const int NoobnessLevelMessageComposer = 880;
    public const int PingMessageComposer = 3116;
    public const int UniqueMachineIDComposer = 3083;
    public const int UserObjectComposer = 3329;
    public const int UserRightsMessageComposer = 1551;
    public const int CommunityVoteReceivedComposer = 1290;
    public const int UserNftChatStylesMessageComposer = 3792;
    public const int UserNftWardrobeMessageComposer = 1827;
    public const int UserNftWardrobeSelectionMessageComposer = 1442;
    public const int LatencyPingResponseMessageComposer = 2170;
    public const int CommunityGoalHallOfFameMessageComposer = 2716;
    public const int CommunityGoalProgressMessageComposer = 3603;
    public const int ConcurrentUsersGoalProgressMessageComposer = 3867;
    public const int EpicPopupMessageComposer = 58;
    public const int QuestCancelledMessageComposer = 1061;
    public const int QuestCompletedMessageComposer = 2996;
    public const int QuestDailyMessageComposer = 128;
    public const int QuestMessageComposer = 2765;
    public const int QuestsMessageComposer = 502;
    public const int SeasonalQuestsMessageComposer = 730;
    public const int ActivityPointsMessageComposer = 2659;
    public const int ClubGiftNotificationComposer = 1527;
    public const int ElementPointerMessageComposer = 431;
    public const int HabboAchievementNotificationMessageComposer = 255;
    public const int HabboActivityPointNotificationMessageComposer = 3303;
    public const int HabboBroadcastMessageComposer = 1117;
    public const int InfoFeedEnableMessageComposer = 3606;
    public const int MOTDNotificationComposer = 742;
    public const int NotificationDialogMessageComposer = 1964;
    public const int OfferRewardDeliveredMessageComposer = 43;
    public const int PetLevelNotificationComposer = 3755;
    public const int RestoreClientMessageComposer = 2587;
    public const int UnseenItemsComposer = 1811;
    public const int PetBreedingResultComposer = 3681;
    public const int PetCommandsMessageComposer = 1090;
    public const int PetExperienceComposer = 1124;
    public const int PetFigureUpdateComposer = 3104;
    public const int PetInfoMessageComposer = 2852;
    public const int PetLevelUpdateComposer = 898;
    public const int PetPlacingErrorComposer = 49;
    public const int PetRespectFailedComposer = 2921;
    public const int PetStatusUpdateComposer = 1988;
    public const int AchievementResolutionCompletedMessageComposer = 3540;
    public const int AchievementResolutionProgressMessageComposer = 3315;
    public const int AchievementResolutionsMessageComposer = 3117;
    public const int PhoneCollectionStateMessageComposer = 1580;
    public const int TryPhoneNumberResultMessageComposer = 468;
    public const int TryVerificationCodeResultMessageComposer = 968;
    public const int FigureSetIdsComposer = 3205;
    public const int AccountPreferencesComposer = 2260;
    public const int Game2FriendsLeaderboardComposer = 1034;
    public const int Game2TotalGroupLeaderboardComposer = 560;
    public const int Game2TotalLeaderboardComposer = 3010;
    public const int Game2WeeklyFriendsLeaderboardComposer = 1439;
    public const int Game2WeeklyGroupLeaderboardComposer = 2356;
    public const int Game2WeeklyLeaderboardComposer = 3482;
    public const int CfhSanctionMessageComposer = 179;
    public const int CfhTopicsInitMessageComposer = 639;
    public const int SanctionStatusComposer = 3916;
    public const int YouAreControllerMessageComposer = 2425;
    public const int YouAreNotControllerMessageComposer = 2303;
    public const int YouAreOwnerMessageComposer = 3451;
    public const int AvatarEffectActivatedMessageComposer = 1844;
    public const int AvatarEffectAddedMessageComposer = 1418;
    public const int AvatarEffectExpiredMessageComposer = 2387;
    public const int AvatarEffectSelectedMessageComposer = 3553;
    public const int AvatarEffectsMessageComposer = 3007;
    public const int TalentLevelUpMessageComposer = 1670;
    public const int TalentTrackLevelMessageComposer = 3235;
    public const int TalentTrackMessageComposer = 950;
    public const int UserClassificationMessageComposer = 1148;
    public const int AccountSafetyLockStatusChangeMessageComposer = 520;
    public const int ApproveNameMessageComposer = 3795;
    public const int ChangeEmailResultComposer = 93;
    public const int EmailStatusResultComposer = 2008;
    public const int ExtendedProfileChangedMessageComposer = 1014;
    public const int ExtendedProfileMessageComposer = 2478;
    public const int GroupDetailsChangedMessageComposer = 632;
    public const int GroupMembershipRequestedMessageComposer = 1210;
    public const int GuildCreatedMessageComposer = 535;
    public const int GuildCreationInfoMessageComposer = 920;
    public const int GuildEditFailedMessageComposer = 2953;
    public const int GuildEditInfoMessageComposer = 785;
    public const int GuildEditorDataMessageComposer = 3712;
    public const int GuildMemberFurniCountInHQMessageComposer = 1525;
    public const int GuildMemberMgmtFailedMessageComposer = 3282;
    public const int GuildMembershipRejectedMessageComposer = 3710;
    public const int GuildMembershipsMessageComposer = 2129;
    public const int GuildMembershipUpdatedMessageComposer = 2335;
    public const int GuildMembersMessageComposer = 2192;
    public const int HabboGroupBadgesMessageComposer = 1312;
    public const int HabboGroupDeactivatedMessageComposer = 3121;
    public const int HabboGroupDetailsMessageComposer = 10;
    public const int HabboGroupJoinFailedMessageComposer = 2237;
    public const int HabboUserBadgesMessageComposer = 1246;
    public const int HandItemReceivedMessageComposer = 240;
    public const int IgnoredUsersMessageComposer = 280;
    public const int IgnoreResultMessageComposer = 726;
    public const int InClientLinkMessageComposer = 2417;
    public const int PetRespectNotificationComposer = 2449;
    public const int PetSupplementedNotificationComposer = 1043;
    public const int RelationshipStatusInfoComposer = 3043;
    public const int RespectNotificationMessageComposer = 241;
    public const int ScrSendKickbackInfoMessageComposer = 2161;
    public const int ScrSendUserInfoComposer = 3143;
    public const int UserNameChangedMessageComposer = 1821;
    public const int PromoArticlesMessageComposer = 2840;
    public const int BuildersClubPlacementWarningMessageComposer = 3718;
    public const int FavoriteMembershipUpdateMessageComposer = 2343;
    public const int FloorHeightMapMessageComposer = 2712;
    public const int FurnitureAliasesMessageComposer = 2859;
    public const int HeightMapMessageComposer = 1733;
    public const int HeightMapUpdateMessageComposer = 1936;
    public const int ItemAddMessageComposer = 1616;
    public const int ItemDataUpdateMessageComposer = 2474;
    public const int ItemRemoveMessageComposer = 1239;
    public const int ItemsMessageComposer = 3174;
    public const int ItemsStateUpdateMessageComposer = 3024;
    public const int ItemStateUpdateMessageComposer = 362;
    public const int ItemUpdateMessageComposer = 595;
    public const int ObjectAddMessageComposer = 349;
    public const int ObjectDataUpdateMessageComposer = 816;
    public const int ObjectRemoveConfirmMessageComposer = 3548;
    public const int ObjectRemoveMessageComposer = 3686;
    public const int ObjectRemoveMultipleMessageComposer = 658;
    public const int ObjectsDataUpdateMessageComposer = 2102;
    public const int ObjectsMessageComposer = 1500;
    public const int ObjectUpdateMessageComposer = 3002;
    public const int RoomEntryInfoMessageComposer = 1293;
    public const int RoomPropertyMessageComposer = 2653;
    public const int RoomVisualizationSettingsComposer = 3657;
    public const int SlideObjectBundleMessageComposer = 2025;
    public const int SpecialRoomEffectMessageComposer = 1611;
    public const int UserChangeMessageComposer = 3052;
    public const int UserRemoveMessageComposer = 2988;
    public const int UsersMessageComposer = 397;
    public const int UserUpdateMessageComposer = 334;
    public const int WiredMovementsMessageComposer = 3278;
    public const int CanCreateRoomComposer = 1137;
    public const int CanCreateRoomEventEvent = 78;
    public const int CategoriesWithVisitorCountComposer = 3613;
    public const int CompetitionRoomsDataMessageComposer = 269;
    public const int ConvertedRoomIdComposer = 3113;
    public const int DoorbellMessageComposer = 3158;
    public const int FavouriteChangedComposer = 421;
    public const int FavouritesComposer = 1876;
    public const int FlatAccessDeniedMessageComposer = 1138;
    public const int FlatCreatedComposer = 1586;
    public const int GetGuestRoomResultComposer = 309;
    public const int GuestRoomSearchResultComposer = 2684;
    public const int NavigatorSettingsComposer = 642;
    public const int OfficialRoomsComposer = 331;
    public const int PopularRoomTagsResultComposer = 2016;
    public const int RoomEventCancelComposer = 1072;
    public const int RoomEventComposer = 1715;
    public const int RoomInfoUpdatedComposer = 1396;
    public const int RoomRatingComposer = 572;
    public const int UserEventCatsEvent = 2054;
    public const int UserFlatCatsComposer = 2959;
    public const int FurniListAddOrUpdateComposer = 3991;
    public const int FurniListComposer = 2604;
    public const int FurniListInvalidateComposer = 1053;
    public const int FurniListRemoveComposer = 914;
    public const int PostItPlacedComposer = 674;
    public const int OpenComposer = 430;
    public const int WiredFurniActionComposer = 2429;
    public const int WiredFurniAddonComposer = 3823;
    public const int WiredFurniConditionComposer = 2360;
    public const int WiredFurniSelectorComposer = 1703;
    public const int WiredFurniTriggerComposer = 2505;
    public const int WiredFurniVariableComposer = 3474;
    public const int WiredRewardResultMessageComposer = 1564;
    public const int WiredSaveSuccessComposer = 3258;
    public const int WiredValidationErrorComposer = 3766;
}

[PublicAPI]
public enum MessageEvent
{
    BreedPetsMessageEvent = 3539,
    CustomizePetWithFurniEvent = 3209,
    GetPetInfoMessageEvent = 2307,
    PetSelectedMessageEvent = 1063,
    RespectPetMessageEvent = 3076,
    ForwardToACompetitionRoomMessageEvent = 489,
    ForwardToASubmittableRoomMessageEvent = 1830,
    ForwardToRandomCompetitionRoomMessageEvent = 3275,
    GetCurrentTimingCodeMessageEvent = 70,
    GetIsUserPartOfCompetitionMessageEvent = 3888,
    GetSecondsUntilMessageEvent = 2445,
    RoomCompetitionInitMessageEvent = 1132,
    SubmitRoomToCompetitionMessageEvent = 2865,
    VoteForRoomMessageEvent = 3657,
    ResetPhoneNumberStateMessageEvent = 2048,
    SetPhoneNumberVerificationStatusMessageEvent = 1676,
    TryPhoneNumberMessageEvent = 691,
    VerifyCodeMessageEvent = 1248,
    CommunityGoalVoteMessageEvent = 2074,
    GetNftCreditsMessageEvent = 1088,
    GetSelectedNftWardrobeOutfitMessageEvent = 2494,
    GetSilverMessageEvent = 3891,
    GetUserNftWardrobeMessageEvent = 1148,
    SaveUserNftWardrobeMessageEvent = 918,
    RoomNetworkOpenConnectionMessageEvent = 1525,
    GetBotInventoryEvent = 3454,
    GetCreditsInfoEvent = 701,
    GetTalentTrackLevelMessageEvent = 1017,
    GetTalentTrackMessageEvent = 3082,
    GuideAdvertisementReadMessageEvent = 3924,
    CallForHelpFromForumMessageMessageEvent = 1436,
    CallForHelpFromForumThreadMessageEvent = 2657,
    CallForHelpFromIMMessageEvent = 869,
    CallForHelpFromPhotoMessageEvent = 3138,
    CallForHelpFromSelfieMessageEvent = 1326,
    CallForHelpMessageEvent = 3455,
    ChatReviewGuideDecidesOnOfferMessageEvent = 1672,
    ChatReviewGuideDetachedMessageEvent = 2861,
    ChatReviewGuideVoteMessageEvent = 2140,
    ChatReviewSessionCreateMessageEvent = 3106,
    DeletePendingCallsForHelpMessageEvent = 1142,
    GetCfhStatusMessageEvent = 3556,
    GetGuideReportingStatusMessageEvent = 2537,
    GetPendingCallsForHelpMessageEvent = 3374,
    GetQuizQuestionsEvent = 1723,
    GuideSessionCreateMessageEvent = 2581,
    GuideSessionFeedbackMessageEvent = 3621,
    GuideSessionGetRequesterRoomMessageEvent = 3236,
    GuideSessionGuideDecidesMessageEvent = 303,
    GuideSessionInviteRequesterMessageEvent = 276,
    GuideSessionIsTypingMessageEvent = 3911,
    GuideSessionMessageMessageEvent = 2315,
    GuideSessionOnDutyUpdateMessageEvent = 1627,
    GuideSessionReportMessageEvent = 2620,
    GuideSessionRequesterCancelsMessageEvent = 2446,
    GuideSessionResolvedMessageEvent = 997,
    PostQuizAnswersEvent = 3803,
    ChangeQueueMessageEvent = 1468,
    OpenFlatConnectionMessageEvent = 927,
    QuitMessageEvent = 3207,
    BuildersClubPlaceRoomItemMessageEvent = 158,
    BuildersClubPlaceWallItemMessageEvent = 763,
    BuildersClubQueryFurniCountMessageEvent = 3147,
    GetBonusRareInfoMessageEvent = 2131,
    GetBundleDiscountRulesetEvent = 1779,
    GetCatalogIndexEvent = 3238,
    GetCatalogPageEvent = 1544,
    GetCatalogPageWithEarliestExpiryEvent = 3702,
    GetClubGiftMessageEvent = 3870,
    GetClubOffersMessageEvent = 1590,
    GetGiftWrappingConfigurationEvent = 3814,
    GetHabboClubExtendOfferMessageEvent = 2360,
    GetIsOfferGiftableEvent = 1777,
    GetLimitedOfferAppearingNextEvent = 503,
    GetNextTargetedOfferEvent = 2039,
    GetProductOfferEvent = 1515,
    GetRoomAdPurchaseInfoEvent = 265,
    GetSeasonalCalendarDailyEvent = 1257,
    GetSellablePetPalettesEvent = 583,
    GetSnowWarGameTokensOfferEvent = 638,
    MarkCatalogNewAdditionsPageOpenedEvent = 81,
    PurchaseBasicMembershipExtensionEvent = 2125,
    PurchaseFromCatalogAsGiftEvent = 1329,
    PurchaseFromCatalogEvent = 289,
    PurchaseRoomAdMessageEvent = 410,
    PurchaseSnowWarGameTokensOfferEvent = 1305,
    PurchaseTargetedOfferEvent = 3317,
    PurchaseVipMembershipExtensionEvent = 3545,
    RedeemVoucherMessageEvent = 3632,
    RoomAdPurchaseInitiatedEvent = 597,
    SelectClubGiftEvent = 893,
    SetTargetedOfferStateEvent = 2905,
    ShopTargetedOfferViewedEvent = 1049,
    NavigatorAddCollapsedCategoryMessageEvent = 2080,
    NavigatorAddSavedSearchEvent = 337,
    NavigatorDeleteSavedSearchEvent = 1449,
    NavigatorRemoveCollapsedCategoryMessageEvent = 2459,
    NavigatorSetSearchCodeViewModeMessageEvent = 459,
    NewNavigatorInitEvent = 991,
    NewNavigatorSearchEvent = 1827,
    GetOccupiedTilesMessageEvent = 3289,
    GetRoomEntryTileMessageEvent = 2538,
    UpdateFloorPropertiesMessageEvent = 2839,
    NewUserExperienceGetGiftsMessageEvent = 950,
    NewUserExperienceScriptProceedEvent = 308,
    SelectInitialRoomEvent = 505,
    GetInterstitialMessageEvent = 1870,
    InterstitialShownMessageEvent = 1595,
    CommandBotEvent = 2408,
    GetBotCommandConfigurationDataEvent = 2052,
    GetBadgePointLimitsEvent = 3213,
    GetBadgesEvent = 1570,
    GetIsBadgeRequestFulfilledEvent = 1284,
    RequestABadgeEvent = 1422,
    SetActivatedBadgesEvent = 388,
    ResetUnseenItemIdsEvent = 2723,
    ResetUnseenItemsEvent = 2378,
    AddAdminRightsToMemberMessageEvent = 464,
    ApproveAllMembershipRequestsMessageEvent = 369,
    ApproveMembershipRequestMessageEvent = 1265,
    ApproveNameMessageEvent = 2835,
    ChangeEmailEvent = 538,
    CreateGuildMessageEvent = 1885,
    DeactivateGuildMessageEvent = 1954,
    DeselectFavouriteHabboGroupMessageEvent = 3045,
    GetEmailStatusEvent = 3295,
    GetExtendedProfileByNameMessageEvent = 1718,
    GetExtendedProfileMessageEvent = 4,
    GetGuildCreationInfoMessageEvent = 2457,
    GetGuildEditInfoMessageEvent = 2956,
    GetGuildEditorDataMessageEvent = 1751,
    GetGuildMembershipsMessageEvent = 175,
    GetGuildMembersMessageEvent = 3581,
    GetHabboGroupBadgesMessageEvent = 1179,
    GetHabboGroupDetailsMessageEvent = 2897,
    GetIgnoredUsersMessageEvent = 1410,
    GetMemberGuildItemCountMessageEvent = 2510,
    GetMOTDMessageEvent = 1398,
    GetRelationshipStatusInfoMessageEvent = 1260,
    GetSelectedBadgesMessageEvent = 5,
    GetUserNftChatStylesMessageEvent = 3569,
    GiveStarGemToUserMessageEvent = 2930,
    IgnoreUserMessageEvent = 2828,
    JoinHabboGroupMessageEvent = 1516,
    KickMemberMessageEvent = 329,
    RejectMembershipRequestMessageEvent = 844,
    RemoveAdminRightsFromMemberMessageEvent = 1580,
    ScrGetKickbackInfoMessageEvent = 3466,
    ScrGetUserInfoMessageEvent = 1215,
    SelectFavouriteHabboGroupMessageEvent = 3312,
    UnblockGroupMemberMessageEvent = 3631,
    UnignoreUserMessageEvent = 3330,
    UpdateGuildBadgeMessageEvent = 1604,
    UpdateGuildColorsMessageEvent = 2710,
    UpdateGuildIdentityMessageEvent = 3848,
    UpdateGuildSettingsMessageEvent = 3955,
    CraftEvent = 1047,
    CraftSecretEvent = 3602,
    GetCraftableProductsEvent = 3560,
    GetCraftingRecipeEvent = 3944,
    GetCraftingRecipesAvailableEvent = 914,
    CloseIssueDefaultActionMessageEvent = 1220,
    CloseIssuesMessageEvent = 2533,
    DefaultSanctionMessageEvent = 3531,
    GetCfhChatlogMessageEvent = 509,
    GetModeratorRoomInfoMessageEvent = 1631,
    GetModeratorUserInfoMessageEvent = 838,
    GetRoomChatlogMessageEvent = 2684,
    GetRoomVisitsMessageEvent = 1078,
    GetUserChatlogMessageEvent = 1727,
    ModAlertMessageEvent = 934,
    ModBanMessageEvent = 322,
    ModerateRoomMessageEvent = 1367,
    ModeratorActionMessageEvent = 196,
    ModKickMessageEvent = 1951,
    ModMessageMessageEvent = 3447,
    ModMuteMessageEvent = 2394,
    ModToolPreferencesEvent = 2597,
    ModToolSanctionEvent = 2631,
    ModTradingLockMessageEvent = 3278,
    PickIssuesMessageEvent = 714,
    ReleaseIssuesMessageEvent = 1272,
    ClientHelloMessageEvent = 4000,
    CompleteDiffieHandshakeMessageEvent = 1057,
    DisconnectMessageEvent = 3136,
    InfoRetrieveMessageEvent = 1240,
    InitDiffieHandshakeMessageEvent = 1360,
    PongMessageEvent = 494,
    SSOTicketMessageEvent = 2127,
    UniqueIDMessageEvent = 1910,
    VersionCheckMessageEvent = 2481,
    AcceptQuestMessageEvent = 327,
    ActivateQuestMessageEvent = 1061,
    CancelQuestMessageEvent = 626,
    FriendRequestQuestCompleteMessageEvent = 2509,
    GetCommunityGoalHallOfFameMessageEvent = 1786,
    GetCommunityGoalProgressMessageEvent = 3303,
    GetConcurrentUsersGoalProgressMessageEvent = 1030,
    GetConcurrentUsersRewardMessageEvent = 3402,
    GetDailyQuestMessageEvent = 1051,
    GetQuestsMessageEvent = 2207,
    GetSeasonalQuestsOnlyMessageEvent = 2617,
    OpenQuestTrackerMessageEvent = 1611,
    RejectQuestMessageEvent = 2491,
    StartCampaignMessageEvent = 2827,
    GetHotLooksMessageEvent = 481,
    ClickFurniMessageEvent = 2547,
    CompostPlantMessageEvent = 2141,
    GetFurnitureAliasesMessageEvent = 1094,
    GetItemDataMessageEvent = 3840,
    GetPetCommandsMessageEvent = 2850,
    GiveSupplementToPetMessageEvent = 863,
    HarvestPetMessageEvent = 33,
    MountPetMessageEvent = 309,
    MoveAvatarMessageEvent = 1842,
    MoveObjectMessageEvent = 3019,
    MovePetMessageEvent = 3018,
    MoveWallItemMessageEvent = 3612,
    PickupObjectMessageEvent = 516,
    PlaceBotMessageEvent = 2137,
    PlaceObjectMessageEvent = 2965,
    PlacePetMessageEvent = 3623,
    RemoveBotFromFlatMessageEvent = 2374,
    RemoveItemMessageEvent = 165,
    RemovePetFromFlatMessageEvent = 1634,
    RemoveSaddleFromPetMessageEvent = 2713,
    SetClothingChangeDataMessageEvent = 3062,
    SetItemDataMessageEvent = 2372,
    SetObjectDataMessageEvent = 2347,
    TogglePetBreedingPermissionMessageEvent = 2775,
    TogglePetRidingPermissionMessageEvent = 1728,
    UseFurnitureMessageEvent = 3971,
    UseWallItemMessageEvent = 1594,
    CreditVaultStatusMessageEvent = 1427,
    IncomeRewardClaimMessageEvent = 947,
    IncomeRewardStatusMessageEvent = 3869,
    WithdrawCreditVaultMessageEvent = 2335,
    OpenCampaignCalendarDoorAsStaffEvent = 1705,
    OpenCampaignCalendarDoorEvent = 3887,
    AcceptTradingEvent = 361,
    AddItemsToTradeEvent = 672,
    AddItemToTradeEvent = 3080,
    CloseTradingEvent = 3425,
    ConfirmAcceptTradingEvent = 357,
    ConfirmDeclineTradingEvent = 3927,
    OpenTradingEvent = 766,
    RemoveItemFromTradeEvent = 1846,
    SilverFeeMessageEvent = 3401,
    UnacceptTradingEvent = 3704,
    UpdateFigureDataMessageEvent = 1606,
    AvatarExpressionMessageEvent = 3314,
    ChangeMottoMessageEvent = 465,
    ChangePostureMessageEvent = 3889,
    CustomizeAvatarWithFurniMessageEvent = 2245,
    DanceMessageEvent = 2083,
    DropCarryItemMessageEvent = 2223,
    LookToMessageEvent = 301,
    PassCarryItemMessageEvent = 2072,
    PassCarryItemToPetMessageEvent = 670,
    SignMessageEvent = 894,
    Game2CheckGameDirectoryStatusMessageEvent = 2354,
    Game2GetAccountGameStatusMessageEvent = 2499,
    Game2LeaveGameMessageEvent = 508,
    Game2QuickJoinGameMessageEvent = 1016,
    Game2StartSnowWarMessageEvent = 2530,
    GetForumsListMessageEvent = 3548,
    GetForumStatsMessageEvent = 3546,
    GetMessagesMessageEvent = 897,
    GetThreadMessageEvent = 2292,
    GetThreadsMessageEvent = 690,
    GetUnreadForumsCountMessageEvent = 1377,
    ModerateMessageMessageEvent = 1464,
    ModerateThreadMessageEvent = 2958,
    PostMessageMessageEvent = 902,
    UpdateForumReadMarkerMessageEvent = 2271,
    UpdateForumSettingsMessageEvent = 1489,
    UpdateThreadMessageEvent = 790,
    AddJukeboxDiskEvent = 2840,
    GetJukeboxPlayListMessageEvent = 2115,
    GetNowPlayingMessageEvent = 2212,
    GetOfficialSongIdMessageEvent = 1089,
    GetSongInfoMessageEvent = 3796,
    GetSoundMachinePlayListMessageEvent = 2092,
    GetSoundSettingsEvent = 3349,
    GetUserSongDisksMessageEvent = 224,
    RemoveJukeboxDiskEvent = 2290,
    ChangeUserNameInRoomMessageEvent = 654,
    ChangeUserNameMessageEvent = 938,
    CheckUserNameMessageEvent = 1009,
    GetWardrobeMessageEvent = 1907,
    SaveWardrobeOutfitMessageEvent = 2313,
    BuyMarketplaceOfferMessageEvent = 2820,
    BuyMarketplaceTokensMessageEvent = 1901,
    CancelMarketplaceOfferMessageEvent = 142,
    GetMarketplaceCanMakeOfferMessageEvent = 3446,
    GetMarketplaceConfigurationMessageEvent = 3464,
    GetMarketplaceItemStatsEvent = 2167,
    GetMarketplaceOffersMessageEvent = 578,
    GetMarketplaceOwnOffersMessageEvent = 630,
    MakeOfferMessageEvent = 1338,
    RedeemMarketplaceOfferCreditsMessageEvent = 453,
    GetAchievementsEvent = 346,
    AddSpamWallPostItMessageEvent = 552,
    ControlYoutubeDisplayPlaybackMessageEvent = 2269,
    CreditFurniRedeemMessageEvent = 3547,
    DiceOffMessageEvent = 2201,
    EnterOneWayDoorMessageEvent = 3768,
    ExtendRentOrBuyoutFurniMessageEvent = 2844,
    ExtendRentOrBuyoutStripItemMessageEvent = 577,
    GetGuildFurniContextMenuInfoMessageEvent = 554,
    GetRentOrBuyoutOfferMessageEvent = 63,
    GetYoutubeDisplayStatusMessageEvent = 2923,
    OpenMysteryTrophyMessageEvent = 1776,
    OpenPetPackageMessageEvent = 770,
    PlacePostItMessageEvent = 3724,
    PresentOpenMessageEvent = 312,
    RentableSpaceCancelRentMessageEvent = 680,
    RentableSpaceRentMessageEvent = 2376,
    RentableSpaceStatusMessageEvent = 2769,
    RoomDimmerChangeStateMessageEvent = 3009,
    RoomDimmerGetPresetsMessageEvent = 2793,
    RoomDimmerSavePresetMessageEvent = 1106,
    SetAreaHideDataEvent = 614,
    SetCustomStackingHeightEvent = 2130,
    SetMannequinFigureEvent = 1352,
    SetMannequinNameEvent = 3124,
    SetRandomStateMessageEvent = 860,
    SetRoomBackgroundColorDataEvent = 2514,
    SetYoutubeDisplayPlaylistMessageEvent = 1426,
    SpinWheelOfFortuneMessageEvent = 323,
    ThrowDiceMessageEvent = 3256,
    GetResolutionAchievementsMessageEvent = 2,
    CancelPetBreedingEvent = 2740,
    ConfirmPetBreedingEvent = 2276,
    GetPetInventoryEvent = 2595,
    EventLogMessageEvent = 1955,
    LagWarningReportMessageEvent = 2580,
    LatencyPingReportMessageEvent = 3134,
    LatencyPingRequestMessageEvent = 3128,
    PerformanceLogMessageEvent = 148,
    FriendFurniConfirmLockMessageEvent = 847,
    Game2MakeSnowballMessageEvent = 2414,
    Game2RequestFullStatusUpdateMessageEvent = 2422,
    Game2SetUserMoveTargetMessageEvent = 1028,
    Game2ThrowSnowballAtHumanMessageEvent = 145,
    Game2ThrowSnowballAtPositionMessageEvent = 2181,
    AvatarEffectActivatedEvent = 3370,
    AvatarEffectSelectedEvent = 2044,
    AddFavouriteRoomMessageEvent = 1439,
    CancelEventMessageEvent = 2029,
    CanCreateRoomMessageEvent = 2677,
    CompetitionRoomsSearchMessageEvent = 3942,
    ConvertGlobalRoomIdMessageEvent = 822,
    CreateFlatMessageEvent = 3061,
    DeleteFavouriteRoomMessageEvent = 2788,
    EditEventMessageEvent = 3200,
    ForwardToARandomPromotedRoomMessageEvent = 3663,
    ForwardToSomeRoomMessageEvent = 3603,
    GetGuestRoomMessageEvent = 3435,
    GetOfficialRoomsMessageEvent = 1362,
    GetPopularRoomTagsMessageEvent = 2948,
    GetUserEventCatsMessageEvent = 687,
    GetUserFlatCatsMessageEvent = 2059,
    GuildBaseSearchMessageEvent = 3488,
    MyFavouriteRoomsSearchMessageEvent = 2283,
    MyFrequentRoomHistorySearchMessageEvent = 490,
    MyFriendsRoomsSearchMessageEvent = 3047,
    MyGuildBasesSearchMessageEvent = 3025,
    MyRecommendedRoomsMessageEvent = 190,
    MyRoomHistorySearchMessageEvent = 352,
    MyRoomRightsSearchMessageEvent = 2573,
    MyRoomsSearchMessageEvent = 2455,
    PopularRoomsSearchMessageEvent = 3378,
    RateFlatMessageEvent = 3951,
    RemoveOwnRoomRightsRoomMessageEvent = 3692,
    RoomAdEventTabAdClickedEvent = 2554,
    RoomAdEventTabViewedEvent = 3415,
    RoomAdSearchMessageEvent = 1403,
    RoomsWhereMyFriendsAreSearchMessageEvent = 1238,
    RoomsWithHighestScoreSearchMessageEvent = 906,
    RoomTextSearchMessageEvent = 3496,
    SetRoomSessionTagsMessageEvent = 394,
    ToggleStaffPickMessageEvent = 2184,
    UpdateHomeRoomMessageEvent = 2724,
    GetCollectibleMintableItemTypesMessageEvent = 1007,
    GetCollectibleMintingEnabledMessageEvent = 896,
    GetCollectibleMintTokensMessageEvent = 1026,
    GetCollectibleWalletAddressesMessageEvent = 458,
    GetCollectorScoreMessageEvent = 3390,
    GetMintTokenOffersMessageEvent = 2322,
    GetNftCollectionsMessageEvent = 378,
    GetNftTransferFeeMessageEvent = 3935,
    MintItemMessageEvent = 783,
    NftCollectiblesClaimBonusItemMessageEvent = 1991,
    NftCollectiblesClaimRewardItemMessageEvent = 1228,
    NftTransferAssetsMessageEvent = 2658,
    PurchaseMintTokenMessageEvent = 2155,
    PeerUsersClassificationMessageEvent = 3698,
    RoomUsersClassificationMessageEvent = 3529,
    MysteryBoxWaitingCanceledMessageEvent = 1184,
    AmbassadorAlertMessageEvent = 2100,
    AssignRightsMessageEvent = 1415,
    BanUserWithDurationMessageEvent = 1558,
    KickUserMessageEvent = 115,
    LetUserInMessageEvent = 3163,
    MuteAllInRoomEvent = 2945,
    MuteUserMessageEvent = 3320,
    RemoveAllRightsMessageEvent = 1778,
    RemoveRightsMessageEvent = 1295,
    UnbanUserFromRoomMessageEvent = 2321,
    UnmuteUserMessageEvent = 2734,
    PollAnswerEvent = 3838,
    PollRejectEvent = 2906,
    PollStartEvent = 3928,
    DeleteRoomMessageEvent = 736,
    GetBannedUsersFromRoomMessageEvent = 342,
    GetCustomRoomFilterMessageEvent = 201,
    GetFlatControllersMessageEvent = 1620,
    GetRoomSettingsMessageEvent = 2417,
    SaveRoomSettingsMessageEvent = 2789,
    UpdateRoomCategoryAndTradeSettingsEvent = 3541,
    UpdateRoomFilterMessageEvent = 2585,
    RequestFurniInventoryEvent = 1163,
    RequestFurniInventoryWhenNotInRoomEvent = 1585,
    RequestRoomPropertySet = 1336,
    Game2GetFriendsLeaderboardEvent = 306,
    Game2GetTotalGroupLeaderboardEvent = 3938,
    Game2GetTotalLeaderboardEvent = 2017,
    Game2GetWeeklyFriendsLeaderboardEvent = 3441,
    Game2GetWeeklyGroupLeaderboardEvent = 1753,
    Game2GetWeeklyLeaderboardEvent = 1143,
    CancelTypingMessageEvent = 3104,
    ChatMessageEvent = 3801,
    ShoutMessageEvent = 445,
    StartTypingMessageEvent = 1497,
    WhisperMessageEvent = 29,
    WiredClearErrorLogsMessageEvent = 3939,
    WiredGetAllVariableHoldersMessageEvent = 317,
    WiredGetAllVariablesDiffsMessageEvent = 3674,
    WiredGetAllVariablesHashMessageEvent = 2476,
    WiredGetErrorLogsMessageEvent = 3765,
    WiredGetRoomSettingsMessageEvent = 3024,
    WiredGetRoomStatsMessageEvent = 1854,
    WiredGetVariablesForObjectMessageEvent = 2379,
    WiredSetObjectVariableValueMessageEvent = 1096,
    WiredSetPreferencesMessageEvent = 2726,
    WiredSetRoomSettingsMessageEvent = 3483,
    AcceptFriendMessageEvent = 80,
    DeclineFriendMessageEvent = 664,
    FindNewFriendsMessageEvent = 353,
    FollowFriendMessageEvent = 1309,
    FriendListUpdateMessageEvent = 1768,
    GetFriendRequestsMessageEvent = 1375,
    GetMessengerHistoryEvent = 2978,
    HabboSearchMessageEvent = 3224,
    MessengerInitMessageEvent = 1437,
    RemoveFriendMessageEvent = 2727,
    RequestFriendMessageEvent = 2794,
    SendMsgMessageEvent = 1314,
    SendRoomInviteMessageEvent = 565,
    SetRelationshipStatusMessageEvent = 1660,
    VisitUserMessageEvent = 773,
    SetChatPreferencesMessageEvent = 2128,
    SetChatStylePreferenceEvent = 3142,
    SetIgnoreRoomInvitesMessageEvent = 3198,
    SetNewNavigatorWindowPreferencesMessageEvent = 2892,
    SetRoomCameraPreferencesMessageEvent = 1571,
    SetSoundSettingsEvent = 2337,
    SetUIFlagsMessageEvent = 3073,
    Game2ExitGameMessageEvent = 1733,
    Game2GameChatMessageEvent = 3214,
    Game2LoadStageReadyMessageEvent = 288,
    Game2PlayAgainMessageEvent = 2725,
    PhotoCompetitionMessageEvent = 3916,
    PublishPhotoMessageEvent = 2697,
    PurchasePhotoMessageEvent = 2464,
    RenderRoomMessageEvent = 2931,
    RenderRoomThumbnailMessageEvent = 620,
    RequestCameraConfigurationMessageEvent = 1958,
    GetPromoArticlesMessageEvent = 719,
    ApplySnapshotMessageEvent = 439,
    OpenMessageEvent = 1332,
    UpdateActionMessageEvent = 3112,
    UpdateAddonMessageEvent = 1473,
    UpdateConditionMessageEvent = 1199,
    UpdateSelectorMessageEvent = 1943,
    UpdateTriggerMessageEvent = 2040,
    UpdateVariableMessageEvent = 704
}